#!/usr/bin/env bash
set -euo pipefail

PRODUCT_DIR="${1:-.}"
PRODUCT_ROOT="$(cd "$PRODUCT_DIR" && pwd)"
errors=0

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  errors=$((errors + 1))
}

for required in \
  .deltafuse/config.yaml \
  .deltafuse/lock.yaml \
  docs/intake \
  docs/changes \
  docs/spec \
  docs/decisions \
  docs/archive/intake \
  docs/archive/changes; do
  [ -e "$PRODUCT_ROOT/$required" ] || fail "Missing required path: $required"
done

for forbidden in docs/process docs/init docs/todo; do
  [ ! -e "$PRODUCT_ROOT/$forbidden" ] || fail "Legacy product path must be migrated: $forbidden"
done

lock="$PRODUCT_ROOT/.deltafuse/lock.yaml"
config="$PRODUCT_ROOT/.deltafuse/config.yaml"
config_version=""
lock_version=""
lock_hash=""
if [ -f "$config" ]; then
  config_version="$(sed -n 's/^  version:[[:space:]]*//p' "$config" | head -n 1)"
  [ -n "$config_version" ] || fail "Config file has no requested framework version"
fi
if [ -f "$lock" ]; then
  lock_version="$(sed -n 's/^  version:[[:space:]]*//p' "$lock" | head -n 1)"
  lock_hash="$(sed -n 's/^  content_hash:[[:space:]]*//p' "$lock" | head -n 1)"
  [ -n "$lock_version" ] || fail "Lock file has no framework version"
  printf '%s' "$lock_hash" | grep -Eq '^sha256:[a-fA-F0-9]{64}$' || fail "Lock file has no valid framework content hash"
fi

if [ -n "$config_version" ] && [ -n "$lock_version" ] && [ "$config_version" != "$lock_version" ]; then
  fail "Requested framework version $config_version does not match locked version $lock_version"
fi

if [ -d "$PRODUCT_ROOT/docs/changes" ]; then
  for change in "$PRODUCT_ROOT"/docs/changes/*; do
    [ -d "$change" ] || continue
    [ -f "$change/change.yaml" ] || fail "Change $(basename "$change") is missing change.yaml"
    [ -f "$change/request.md" ] || fail "Change $(basename "$change") is missing request.md"
  done
fi

skills="intake analyze-change specify-change decompose-change target-task implement-task verify-change"
for adapter in .agents/skills .cursor/skills .gemini/skills; do
  [ -d "$PRODUCT_ROOT/$adapter" ] || continue
  for skill in $skills; do
    skill_root="$PRODUCT_ROOT/$adapter/$skill"
    [ -f "$skill_root/SKILL.md" ] || { fail "Missing generated skill: $adapter/$skill/SKILL.md"; continue; }
    marker="$skill_root/.deltafuse-generated.yaml"
    [ -f "$marker" ] || { fail "Missing generated metadata: $adapter/$skill"; continue; }
    grep -Fq '# DO NOT EDIT: generated by DeltaFuse installer.' "$skill_root/SKILL.md" || fail "Generated skill is not marked DO NOT EDIT: $adapter/$skill"
    [ -z "$lock_version" ] || grep -Fq "generated_by: deltafuse@$lock_version" "$marker" || fail "Generated skill version mismatch: $adapter/$skill"
    [ -z "$lock_hash" ] || grep -Fq "content_hash: $lock_hash" "$marker" || fail "Generated skill hash mismatch: $adapter/$skill"
  done
done

if [ "$errors" -ne 0 ]; then
  exit 1
fi

printf 'DeltaFuse product layout is valid.\n'
