import pytest
from pathlib import Path
import os
import shutil
import subprocess
import sys
import yaml
from deltafuse.core.hasher import compute_framework_content_hash
from deltafuse.core.installer import install, InstallationError

def test_framework_content_hash_consistency(repo_root: Path):
    hash1 = compute_framework_content_hash(repo_root)
    hash2 = compute_framework_content_hash(repo_root)
    assert hash1 == hash2
    assert len(hash1) == 64
    assert all(c in "0123456789abcdef" for c in hash1)

def test_fresh_installation(tmp_path: Path, repo_root: Path):
    result = install(target_dir=tmp_path, framework_root=repo_root)
    assert result.version == (repo_root / "VERSION").read_text(encoding="utf-8").strip()
    assert len(result.content_hash) == 64

    # Check directories
    assert (tmp_path / ".deltafuse").is_dir()
    assert (tmp_path / "docs" / "intake").is_dir()
    assert (tmp_path / "docs" / "changes").is_dir()
    assert (tmp_path / "docs" / "spec").is_dir()
    assert (tmp_path / "docs" / "decisions").is_dir()
    assert (tmp_path / "docs" / "archive" / "changes").is_dir()

    # Check files
    assert (tmp_path / "AGENTS.md").is_file()
    assert (tmp_path / ".deltafuse" / "config.yaml").is_file()
    assert (tmp_path / ".deltafuse" / "lock.yaml").is_file()
    lock = yaml.safe_load((tmp_path / ".deltafuse" / "lock.yaml").read_text(encoding="utf-8"))
    assert lock["workflow"]["call_width"] == "wide"
    assert lock["workflow"]["auto_accept_decisions"] is False
    cfg = yaml.safe_load((tmp_path / ".deltafuse" / "config.yaml").read_text(encoding="utf-8"))
    assert cfg["workflow"]["call_width"] == "wide"
    assert cfg["workflow"]["leash"] == "off"
    assert not (tmp_path / ".git" / "hooks" / "pre-commit").exists()
    workflow = (tmp_path / ".github" / "workflows" / "deltafuse-leash.yml").read_text(encoding="utf-8")
    assert "deltafuse leash" in workflow
    assert "pytest" in workflow
    assert "docs/contracts" not in workflow
    assert (tmp_path / "docs" / "spec" / "_capabilities.yaml").is_file()
    assert (tmp_path / "docs" / "decisions" / "DEC-0000-template.md").is_file()
    assert (tmp_path / "CHANGELOG.md").is_file()

    # Check generated skills
    agents_skills = tmp_path / ".agents" / "skills"
    assert (agents_skills / "intake" / "SKILL.md").is_file()
    assert (agents_skills / "analyze" / ".deltafuse-generated.yaml").is_file()
    intake = (agents_skills / "intake" / "SKILL.md").read_text(encoding="utf-8")
    assert "binds the Worker to an LLM" in intake
    assert "--gate intake" in intake
    assert "# DO NOT EDIT: generated by DeltaFuse installer." in intake
    assert not (agents_skills / "intake").is_symlink()
    assert result.adapter_mode == "copy"
    agents = (tmp_path / "AGENTS.md").read_text(encoding="utf-8")
    assert "The Core" in agents
    assert "The Worker" in agents
    assert "workflow.leash" in agents

def test_idempotent_upgrade_preserves_custom_files(tmp_path: Path, repo_root: Path):
    # Step 1: initial install
    install(target_dir=tmp_path, framework_root=repo_root)

    # Step 2: mutate user files
    custom_agents = "# Custom User Agent Config\n"
    (tmp_path / "AGENTS.md").write_text(custom_agents, encoding="utf-8")

    custom_capabilities = """schema_version: 2
domains:
  custom_domain:
    summary: Custom user domain
    capabilities: {}
"""
    (tmp_path / "docs" / "spec" / "_capabilities.yaml").write_text(custom_capabilities, encoding="utf-8")

    # Step 3: run install again without force
    install(target_dir=tmp_path, framework_root=repo_root)

    # Verify custom content preserved
    assert (tmp_path / "AGENTS.md").read_text(encoding="utf-8") == custom_agents
    assert (tmp_path / "docs" / "spec" / "_capabilities.yaml").read_text(encoding="utf-8") == custom_capabilities

def test_force_upgrade_with_modified_lock(tmp_path: Path, repo_root: Path):
    install(target_dir=tmp_path, framework_root=repo_root)

    lock_file = tmp_path / ".deltafuse" / "lock.yaml"
    lock_file.write_text("schema_version: 2\nframework:\n  version: 1.0.0\n  content_hash: sha256:0000000000000000000000000000000000000000000000000000000000000000\n", encoding="utf-8")

    # Without force: must raise InstallationError
    with pytest.raises(InstallationError, match="A different DeltaFuse lock already exists"):
        install(target_dir=tmp_path, force=False, framework_root=repo_root)

    # With force: must succeed and update lock
    result = install(target_dir=tmp_path, force=True, framework_root=repo_root)
    assert f"content_hash: sha256:{result.content_hash}" in lock_file.read_text(encoding="utf-8")
    lock = yaml.safe_load(lock_file.read_text(encoding="utf-8"))
    assert lock["workflow"]["call_width"] == "wide"


def test_install_pins_narrow_call_width_from_config(tmp_path: Path, repo_root: Path):
    install(target_dir=tmp_path, framework_root=repo_root)
    cfg_path = tmp_path / ".deltafuse" / "config.yaml"
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    cfg["workflow"]["call_width"] = "narrow"
    cfg_path.write_text(yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
    install(target_dir=tmp_path, framework_root=repo_root)
    lock = yaml.safe_load((tmp_path / ".deltafuse" / "lock.yaml").read_text(encoding="utf-8"))
    assert lock["workflow"]["call_width"] == "narrow"


def test_install_rejects_invalid_call_width(tmp_path: Path, repo_root: Path):
    install(target_dir=tmp_path, framework_root=repo_root)
    cfg_path = tmp_path / ".deltafuse" / "config.yaml"
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    cfg["workflow"]["call_width"] = "ornith"
    cfg_path.write_text(yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
    with pytest.raises(InstallationError, match="call_width"):
        install(target_dir=tmp_path, framework_root=repo_root)


def _nested_product(tmp_path: Path, repo_root: Path) -> tuple[Path, Path]:
    product = tmp_path / "product"
    vendor = product / "vendor" / "delta-fuse"
    (vendor / "docs").mkdir(parents=True)
    (vendor / "scripts").mkdir()
    (vendor / "tests").mkdir()
    (vendor / "docs" / ".keep").write_text("", encoding="utf-8")
    (vendor / "scripts" / ".keep").write_text("", encoding="utf-8")
    (vendor / "tests" / ".keep").write_text("", encoding="utf-8")
    shutil.copytree(repo_root / "process", vendor / "process")
    shutil.copyfile(repo_root / "VERSION", vendor / "VERSION")
    return product, vendor


def test_nested_checkout_links_adapter_skills(tmp_path: Path, repo_root: Path):
    product, vendor = _nested_product(tmp_path, repo_root)
    result = install(target_dir=product, framework_root=vendor)
    if result.adapter_mode != "link":
        pytest.skip("OS refused skill symlinks")
    skill = product / ".cursor" / "skills" / "analyze"
    from deltafuse.core.adapters import is_link_path
    assert is_link_path(skill)
    text = (skill / "SKILL.md").read_text(encoding="utf-8")
    assert "DO NOT EDIT" not in text
    marker = (product / ".cursor" / "skills" / ".deltafuse-generated.yaml").read_text(encoding="utf-8")
    assert "mode: link" in marker
    lock = yaml.safe_load((product / ".deltafuse" / "lock.yaml").read_text(encoding="utf-8"))
    assert lock["framework"]["source"] == "vendor/delta-fuse"
    from deltafuse.core.layout import validate_product_layout
    assert validate_product_layout(product) == []


def test_nested_checkout_copy_mode_stamps_skills(tmp_path: Path, repo_root: Path):
    product, vendor = _nested_product(tmp_path, repo_root)
    (product / ".deltafuse").mkdir(parents=True)
    cfg = (repo_root / "process" / "templates" / ".deltafuse" / "config.yaml").read_text(encoding="utf-8")
    cfg = cfg.replace("mode: auto", "mode: copy")
    (product / ".deltafuse" / "config.yaml").write_text(cfg, encoding="utf-8")
    result = install(target_dir=product, framework_root=vendor, force=True)
    from deltafuse.core.adapters import is_link_path
    assert result.adapter_mode == "copy"
    skill = product / ".cursor" / "skills" / "analyze"
    assert not is_link_path(skill)
    assert "DO NOT EDIT" in (skill / "SKILL.md").read_text(encoding="utf-8")


def test_explicit_link_without_nested_checkout_fails(tmp_path: Path, repo_root: Path):
    install(target_dir=tmp_path, framework_root=repo_root)
    cfg_path = tmp_path / ".deltafuse" / "config.yaml"
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    cfg["adapters"]["mode"] = "link"
    cfg_path.write_text(yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
    with pytest.raises(InstallationError, match="not inside the product"):
        install(target_dir=tmp_path, force=True, framework_root=repo_root)


def _git(args: list[str], cwd: Path, env: dict[str, str] | None = None, check: bool = True):
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        env=env,
        check=check,
        capture_output=True,
        text=True,
    )


def _leash_env(repo_root: Path) -> dict[str, str]:
    env = os.environ.copy()
    env["DELTAFUSE_PYTHON"] = sys.executable
    src = str(repo_root / "src")
    env["PYTHONPATH"] = src + os.pathsep + env.get("PYTHONPATH", "")
    env["GIT_AUTHOR_NAME"] = "leash"
    env["GIT_AUTHOR_EMAIL"] = "leash@test"
    env["GIT_COMMITTER_NAME"] = "leash"
    env["GIT_COMMITTER_EMAIL"] = "leash@test"
    return env


def _commit(product: Path, message: str, env: dict[str, str], check: bool = True):
    return _git(
        [
            "-c",
            "user.email=leash@test",
            "-c",
            "user.name=leash",
            "-c",
            "commit.gpgsign=false",
            "-c",
            "core.hooksPath=.git/hooks",
            "commit",
            "-m",
            message,
        ],
        cwd=product,
        env=env,
        check=check,
    )


def _set_leash(product: Path, mode: str) -> None:
    cfg_path = product / ".deltafuse" / "config.yaml"
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    cfg.setdefault("workflow", {})["leash"] = mode
    cfg_path.write_text(yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")


def test_install_rejects_invalid_leash(tmp_path: Path, repo_root: Path):
    install(target_dir=tmp_path, framework_root=repo_root)
    cfg_path = tmp_path / ".deltafuse" / "config.yaml"
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    cfg["workflow"]["leash"] = "banana"
    cfg_path.write_text(yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
    with pytest.raises(InstallationError, match="leash"):
        install(target_dir=tmp_path, framework_root=repo_root)


def test_enforce_hook_blocks_orphan_src_commit(tmp_path: Path, repo_root: Path):
    env = _leash_env(repo_root)
    _git(["init"], cwd=tmp_path, env=env)
    install(target_dir=tmp_path, framework_root=repo_root)
    assert not (tmp_path / ".git" / "hooks" / "pre-commit").exists()
    _git(["add", "-A"], cwd=tmp_path, env=env)
    first = _commit(tmp_path, "init", env)
    assert first.returncode == 0
    _set_leash(tmp_path, "enforce")
    install(target_dir=tmp_path, force=True, framework_root=repo_root)
    hook = tmp_path / ".git" / "hooks" / "pre-commit"
    assert hook.is_file()
    assert "deltafuse leash" in hook.read_text(encoding="utf-8")
    src = tmp_path / "src" / "x.py"
    src.parent.mkdir(parents=True, exist_ok=True)
    src.write_text("print(1)\n", encoding="utf-8")
    _git(["add", "src/x.py"], cwd=tmp_path, env=env)
    blocked = _commit(tmp_path, "orphan", env, check=False)
    assert blocked.returncode != 0


def test_advisory_hook_allows_orphan_commit(tmp_path: Path, repo_root: Path):
    env = _leash_env(repo_root)
    _git(["init"], cwd=tmp_path, env=env)
    install(target_dir=tmp_path, framework_root=repo_root)
    _git(["add", "-A"], cwd=tmp_path, env=env)
    _commit(tmp_path, "init", env)
    _set_leash(tmp_path, "advisory")
    install(target_dir=tmp_path, force=True, framework_root=repo_root)
    assert (tmp_path / ".git" / "hooks" / "pre-commit").is_file()
    src = tmp_path / "src" / "x.py"
    src.parent.mkdir(parents=True, exist_ok=True)
    src.write_text("print(1)\n", encoding="utf-8")
    _git(["add", "src/x.py"], cwd=tmp_path, env=env)
    allowed = _commit(tmp_path, "advisory orphan", env, check=False)
    assert allowed.returncode == 0


def test_enforce_does_not_overwrite_foreign_pre_commit(tmp_path: Path, repo_root: Path):
    env = _leash_env(repo_root)
    _git(["init"], cwd=tmp_path, env=env)
    hooks = tmp_path / ".git" / "hooks"
    hooks.mkdir(parents=True, exist_ok=True)
    foreign = hooks / "pre-commit"
    foreign.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8", newline="\n")
    install(target_dir=tmp_path, framework_root=repo_root)
    _set_leash(tmp_path, "enforce")
    install(target_dir=tmp_path, force=True, framework_root=repo_root)
    assert foreign.read_text(encoding="utf-8") == "#!/bin/sh\nexit 0\n"
    managed = tmp_path / ".deltafuse" / "hooks" / "pre-commit"
    assert managed.is_file()
    assert "deltafuse leash" in managed.read_text(encoding="utf-8")
