[CmdletBinding()]
param(
    [string]$ProductDir = "."
)

$ErrorActionPreference = "Stop"
$ProductRoot = [System.IO.Path]::GetFullPath($ProductDir)
$Errors = [System.Collections.Generic.List[string]]::new()

function Require-Path {
    param([string]$RelativePath)
    if (-not (Test-Path -LiteralPath (Join-Path $ProductRoot $RelativePath))) {
        $Errors.Add("Missing required path: $RelativePath")
    }
}

foreach ($required in @(
    ".deltafuse/config.yaml",
    ".deltafuse/lock.yaml",
    "docs/intake",
    "docs/changes",
    "docs/spec",
    "docs/decisions",
    "docs/archive/intake",
    "docs/archive/changes"
)) {
    Require-Path $required
}

foreach ($forbidden in @("docs/process", "docs/init", "docs/todo")) {
    if (Test-Path -LiteralPath (Join-Path $ProductRoot $forbidden)) {
        $Errors.Add("Legacy product path must be migrated: $forbidden")
    }
}

$lockPath = Join-Path $ProductRoot ".deltafuse/lock.yaml"
$lockVersion = $null
$lockHash = $null
$configVersion = $null
$configPath = Join-Path $ProductRoot ".deltafuse/config.yaml"
if (Test-Path -LiteralPath $configPath) {
    $config = Get-Content -LiteralPath $configPath -Raw
    $configVersionMatch = [regex]::Match($config, '(?m)^\s{2}version:\s*(\S+)\s*$')
    if (-not $configVersionMatch.Success) {
        $Errors.Add("Config file has no requested framework version")
    } else {
        $configVersion = $configVersionMatch.Groups[1].Value
    }
}

if (Test-Path -LiteralPath $lockPath) {
    $lock = Get-Content -LiteralPath $lockPath -Raw
    $versionMatch = [regex]::Match($lock, '(?m)^\s{2}version:\s*(\S+)\s*$')
    $hashMatch = [regex]::Match($lock, '(?m)^\s{2}content_hash:\s*(sha256:[a-fA-F0-9]{64})\s*$')
    if (-not $versionMatch.Success) {
        $Errors.Add("Lock file has no framework version")
    } else {
        $lockVersion = $versionMatch.Groups[1].Value
    }
    if (-not $hashMatch.Success) {
        $Errors.Add("Lock file has no valid framework content hash")
    } else {
        $lockHash = $hashMatch.Groups[1].Value.ToLowerInvariant()
    }
}

if ($configVersion -and $lockVersion -and $configVersion -ne $lockVersion) {
    $Errors.Add("Requested framework version $configVersion does not match locked version $lockVersion")
}

$changesRoot = Join-Path $ProductRoot "docs/changes"
if (Test-Path -LiteralPath $changesRoot) {
    Get-ChildItem -LiteralPath $changesRoot -Directory | ForEach-Object {
        foreach ($requiredFile in @("change.yaml", "request.md")) {
            if (-not (Test-Path -LiteralPath (Join-Path $_.FullName $requiredFile))) {
                $Errors.Add("Change $($_.Name) is missing $requiredFile")
            }
        }
    }
}

$skillNames = @("intake", "analyze-change", "specify-change", "decompose-change", "target-task", "implement-task", "verify-change")
foreach ($adapterRootRelative in @(".agents/skills", ".cursor/skills", ".gemini/skills")) {
    $adapterRoot = Join-Path $ProductRoot $adapterRootRelative
    if (-not (Test-Path -LiteralPath $adapterRoot)) {
        continue
    }

    foreach ($skillName in $skillNames) {
        $skillRoot = Join-Path $adapterRoot $skillName
        $skillFile = Join-Path $skillRoot "SKILL.md"
        $marker = Join-Path $skillRoot ".deltafuse-generated.yaml"
        if (-not (Test-Path -LiteralPath $skillFile)) {
            $Errors.Add("Missing generated skill: $adapterRootRelative/$skillName/SKILL.md")
            continue
        }
        if (-not (Test-Path -LiteralPath $marker)) {
            $Errors.Add("Missing generated metadata: $adapterRootRelative/$skillName")
            continue
        }

        $skillContent = Get-Content -LiteralPath $skillFile -Raw
        if ($skillContent -notmatch '(?m)^# DO NOT EDIT: generated by DeltaFuse installer\.$') {
            $Errors.Add("Generated skill is not marked DO NOT EDIT: $adapterRootRelative/$skillName")
        }
        $metadata = Get-Content -LiteralPath $marker -Raw
        if ($lockVersion -and $metadata -notmatch [regex]::Escape("generated_by: deltafuse@$lockVersion")) {
            $Errors.Add("Generated skill version mismatch: $adapterRootRelative/$skillName")
        }
        if ($lockHash -and $metadata -notmatch [regex]::Escape("content_hash: $lockHash")) {
            $Errors.Add("Generated skill hash mismatch: $adapterRootRelative/$skillName")
        }
    }
}

if ($Errors.Count -gt 0) {
    $Errors | ForEach-Object { Write-Error $_ }
    exit 1
}

Write-Host "DeltaFuse product layout is valid." -ForegroundColor Green
