#!/usr/bin/env bash
# DeltaFuse v2 product installer
set -euo pipefail

TARGET_DIR="."
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    *) TARGET_DIR="$arg" ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_ROOT="$(mkdir -p "$TARGET_DIR" && cd "$TARGET_DIR" && pwd)"
FRAMEWORK_VERSION="$(tr -d '\r\n' < "$SCRIPT_DIR/VERSION")"
SCHEMA_VERSION=2

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

framework_hash() {
  local manifest result
  manifest="$(mktemp)"
  {
    for root in docs process scripts tests; do
      if [ -d "$SCRIPT_DIR/$root" ]; then
        # Must stay in sync with src/deltafuse/core/hasher.py: skip transient caches
        find "$SCRIPT_DIR/$root" -type f -print | grep -Ev '/(__pycache__|\.pytest_cache)/' || true
      fi
    done
    printf '%s\n' "$SCRIPT_DIR/VERSION"
  } | while IFS= read -r file; do
    relative="$(printf '%s' "${file#"$SCRIPT_DIR/"}" | tr '[:upper:]' '[:lower:]')"
    printf '%s:%s\n' "$relative" "$(sha256_file "$file")"
  done | LC_ALL=C sort > "$manifest"
  result="$(sha256_file "$manifest")"
  rm -f -- "$manifest"
  printf '%s\n' "$result"
}

copy_template() {
  local source_relative="$1"
  local target_relative="$2"
  local target="$TARGET_ROOT/$target_relative"
  mkdir -p "$(dirname "$target")"
  if [ -e "$target" ]; then
    printf 'Preserving existing %s\n' "$target_relative"
    return
  fi
  cp "$SCRIPT_DIR/$source_relative" "$target"
}

install_generated_skills() {
  local adapter_relative="$1"
  local content_hash="$2"
  local adapter_root="$TARGET_ROOT/$adapter_relative"
  mkdir -p "$adapter_root"

  for source in "$SCRIPT_DIR"/process/skills/*; do
    [ -d "$source" ] || continue
    skill_name="$(basename "$source")"
    destination="$adapter_root/$skill_name"
    marker="$destination/.deltafuse-generated.yaml"

    if [ -e "$destination" ]; then
      if [ ! -f "$marker" ]; then
        printf 'WARNING: preserving non-generated skill %s/%s\n' "$adapter_relative" "$skill_name" >&2
        continue
      fi
      rm -rf -- "$destination"
    fi

    cp -R "$source" "$destination"
    skill_file="$destination/SKILL.md"
    temporary="$(mktemp)"
    awk -v version="$FRAMEWORK_VERSION" -v name="$skill_name" -v hash="$content_hash" '
      NR == 1 && $0 == "---" {
        print
        print "# DO NOT EDIT: generated by DeltaFuse installer."
        print "# deltafuse-version: " version
        print "# deltafuse-source: deltafuse://v" version "/skills/" name
        print "# deltafuse-content-hash: sha256:" hash
        next
      }
      { print }
    ' "$skill_file" > "$temporary"
    mv "$temporary" "$skill_file"

    cat > "$marker" <<EOF
generated_by: deltafuse@$FRAMEWORK_VERSION
source: deltafuse://v$FRAMEWORK_VERSION/skills/$skill_name
content_hash: sha256:$content_hash
EOF
  done
}

printf 'Installing DeltaFuse %s into %s...\n' "$FRAMEWORK_VERSION" "$TARGET_ROOT"
FRAMEWORK_HASH="$(framework_hash)"
LOCK_PATH="$TARGET_ROOT/.deltafuse/lock.yaml"

if [ -f "$LOCK_PATH" ] && [ "$FORCE" -ne 1 ] && ! grep -Fq "content_hash: sha256:$FRAMEWORK_HASH" "$LOCK_PATH"; then
  printf 'A different DeltaFuse lock already exists. Rerun with --force for an explicit upgrade.\n' >&2
  exit 1
fi

mkdir -p \
  "$TARGET_ROOT/.deltafuse" \
  "$TARGET_ROOT/docs/intake" \
  "$TARGET_ROOT/docs/changes" \
  "$TARGET_ROOT/docs/spec" \
  "$TARGET_ROOT/docs/decisions" \
  "$TARGET_ROOT/docs/archive/intake" \
  "$TARGET_ROOT/docs/archive/changes"

config_existed=0
if [ -f "$TARGET_ROOT/.deltafuse/config.yaml" ]; then
  config_existed=1
fi

copy_template process/templates/AGENTS.md AGENTS.md
copy_template process/templates/.deltafuse/config.yaml .deltafuse/config.yaml
copy_template process/templates/docs/intake/README.md docs/intake/README.md
copy_template process/templates/docs/changes/README.md docs/changes/README.md
copy_template process/templates/docs/spec/README.md docs/spec/README.md
copy_template process/templates/docs/spec/context.md docs/spec/context.md
copy_template process/templates/docs/spec/_capabilities.yaml docs/spec/_capabilities.yaml
copy_template process/templates/docs/decisions/README.md docs/decisions/README.md
copy_template process/templates/docs/decisions/DEC-0000-template.md docs/decisions/DEC-0000-template.md
copy_template process/templates/docs/archive/README.md docs/archive/README.md
copy_template process/templates/docs/archive/intake/README.md docs/archive/intake/README.md
copy_template process/templates/docs/archive/changes/README.md docs/archive/changes/README.md
copy_template process/templates/CHANGELOG.md CHANGELOG.md

config_file="$TARGET_ROOT/.deltafuse/config.yaml"
config_source=""
if [ -f "$config_file" ]; then
  config_source="$(awk '/^  source:[[:space:]]*/ { sub(/^  source:[[:space:]]*/, ""); sub(/[[:space:]]+$/, ""); print; exit }' "$config_file")"
fi

effective_source="deltafuse://v$FRAMEWORK_VERSION"
if [ -n "$config_source" ] && [ "$config_source" != "deltafuse" ] && [[ ! "$config_source" =~ ^deltafuse:// ]]; then
  effective_source="$config_source"
fi

if [ -f "$config_file" ] && { [ "$config_existed" -eq 0 ] || [ "$FORCE" -eq 1 ]; }; then
  temporary="$(mktemp)"
  awk -v version="$FRAMEWORK_VERSION" -v source="$effective_source" '
    !updated_ver && /^  version:[[:space:]]*/ {
      print "  version: " version
      updated_ver=1
      next
    }
    !updated_src && /^  source:[[:space:]]*(deltafuse|deltafuse:\/\/[^[:space:]]*)[[:space:]]*$/ {
      print "  source: " source
      updated_src=1
      next
    }
    { print }
    END { if (!updated_ver) exit 42 }
  ' "$config_file" > "$temporary" || {
    status=$?
    rm -f -- "$temporary"
    if [ "$status" -eq 42 ]; then
      printf 'Cannot update framework version: .deltafuse/config.yaml has no indented version field.
' >&2
    fi
    exit "$status"
  }
  mv "$temporary" "$config_file"
fi

cat > "$LOCK_PATH" <<EOF
schema_version: $SCHEMA_VERSION
framework:
  version: $FRAMEWORK_VERSION
  source: $effective_source
  content_hash: sha256:$FRAMEWORK_HASH
EOF

adapter_roots=()
if [ -f "$config_file" ]; then
  while IFS= read -r root; do
    [ -n "$root" ] && adapter_roots+=("$root")
  done < <(awk '
    /^adapters:[[:space:]]*$/ { in_adapters=1; next }
    in_adapters && /^[[:space:]]+roots:[[:space:]]*$/ { in_roots=1; next }
    in_roots && /^[[:space:]]+-[[:space:]]+/ {
      sub(/^[[:space:]]+-[[:space:]]+/, "")
      sub(/[[:space:]]+$/, "")
      print
      next
    }
    in_roots && /^[^[:space:]]/ { in_adapters=0; in_roots=0 }
  ' "$config_file")
fi

if [ ${#adapter_roots[@]} -eq 0 ]; then
  adapter_roots=(.agents/skills .cursor/skills .gemini/skills)
fi

for root in "${adapter_roots[@]}"; do
  install_generated_skills "$root" "$FRAMEWORK_HASH"
done

printf 'DeltaFuse installed. Canonical process remains external; product state is under docs/.\n'
