# DeltaFuse v2 product installer for PowerShell
[CmdletBinding()]
param(
    [string]$TargetDir = ".",
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$FrameworkRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$TargetRoot = [System.IO.Path]::GetFullPath($TargetDir)
$FrameworkVersion = (Get-Content -LiteralPath (Join-Path $FrameworkRoot "VERSION") -Raw).Trim()
$SchemaVersion = 2

function Get-FrameworkContentHash {
    $roots = @("docs", "process", "scripts", "tests")
    $records = foreach ($root in $roots) {
        $absolute = Join-Path $FrameworkRoot $root
        if (Test-Path -LiteralPath $absolute) {
            Get-ChildItem -LiteralPath $absolute -Recurse -File | ForEach-Object {
                # Must stay in sync with src/deltafuse/core/hasher.py: skip transient caches
                if ($_.FullName -match '(__pycache__|\.pytest_cache)[\\/]') { return }
                $relative = $_.FullName.Substring($FrameworkRoot.Length).TrimStart('\', '/').Replace('\', '/').ToLowerInvariant()
                $fileHash = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
                "$relative`:$fileHash"
            }
        }
    }
    $versionPath = Join-Path $FrameworkRoot "VERSION"
    $versionHash = (Get-FileHash -LiteralPath $versionPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $records += "version:$versionHash"

    $orderedRecords = [string[]]$records
    [System.Array]::Sort($orderedRecords, [System.StringComparer]::Ordinal)
    $payload = ($orderedRecords -join "`n") + "`n"
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($payload)
    $hasher = [System.Security.Cryptography.SHA256]::Create()
    try {
        return ([System.BitConverter]::ToString($hasher.ComputeHash($bytes))).Replace("-", "").ToLowerInvariant()
    }
    finally {
        $hasher.Dispose()
    }
}

function Copy-TemplateFile {
    param([string]$SourceRelative, [string]$TargetRelative)

    $source = Join-Path $FrameworkRoot $SourceRelative
    $target = Join-Path $TargetRoot $TargetRelative
    $parent = Split-Path -Parent $target
    New-Item -ItemType Directory -Path $parent -Force | Out-Null

    if (Test-Path -LiteralPath $target) {
        Write-Host "Preserving existing $TargetRelative" -ForegroundColor DarkYellow
        return
    }

    Copy-Item -LiteralPath $source -Destination $target -Force
}

function Get-NestedFrameworkRel {
    $fw = [System.IO.Path]::GetFullPath($FrameworkRoot).TrimEnd('\', '/')
    $tgt = [System.IO.Path]::GetFullPath($TargetRoot).TrimEnd('\', '/')
    if ([string]::Equals($fw, $tgt, [System.StringComparison]::OrdinalIgnoreCase)) {
        return "."
    }
    $prefix = $tgt + [System.IO.Path]::DirectorySeparatorChar
    if ($fw.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $fw.Substring($prefix.Length).Replace('\', '/')
    }
    return $null
}

function Get-RelativePath {
    param([string]$FromDir, [string]$ToPath)
    $fromFull = [System.IO.Path]::GetFullPath($FromDir).TrimEnd('\') + '\'
    $toFull = [System.IO.Path]::GetFullPath($ToPath)
    $fromUri = New-Object System.Uri $fromFull
    $toUri = New-Object System.Uri $toFull
    return [System.Uri]::UnescapeDataString($fromUri.MakeRelativeUri($toUri).ToString()).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
}

function Test-ReparsePoint {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        return $false
    }
    $item = Get-Item -LiteralPath $Path -Force
    return [bool]$item.LinkType
}

function Remove-SkillSlot {
    param([string]$Destination)
    if (-not (Test-Path -LiteralPath $Destination)) {
        return
    }
    if (Test-ReparsePoint $Destination) {
        Remove-Item -LiteralPath $Destination -Force
        return
    }
    Remove-Item -LiteralPath $Destination -Recurse -Force
}

function Test-GeneratedSkillSlot {
    param([string]$Destination)
    if (Test-ReparsePoint $Destination) { return $true }
    return Test-Path -LiteralPath (Join-Path $Destination ".deltafuse-generated.yaml")
}

function New-DirLink {
    param([string]$LinkPath, [string]$TargetPath)
    $rel = Get-RelativePath (Split-Path -Parent $LinkPath) $TargetPath
    try {
        New-Item -ItemType SymbolicLink -Path $LinkPath -Target $rel -ErrorAction Stop | Out-Null
        return $true
    } catch {
        try {
            New-Item -ItemType Junction -Path $LinkPath -Target ([System.IO.Path]::GetFullPath($TargetPath)) -ErrorAction Stop | Out-Null
            return $true
        } catch {
            return $false
        }
    }
}

function Install-SkillCopy {
    param([string]$Source, [string]$Destination, [string]$SkillName, [string]$ContentHash)
    Copy-Item -LiteralPath $Source -Destination $Destination -Recurse -Force
    $skillFile = Join-Path $Destination "SKILL.md"
    $skillContent = Get-Content -LiteralPath $skillFile -Raw
    $banner = "---`n# DO NOT EDIT: generated by DeltaFuse installer.`n# deltafuse-version: $FrameworkVersion`n# deltafuse-source: deltafuse://v$FrameworkVersion/skills/$skillName`n# deltafuse-content-hash: sha256:$ContentHash`n"
    $skillContent = [regex]::Replace($skillContent, '\A---\r?\n', $banner)
    Set-Content -LiteralPath $skillFile -Value $skillContent -Encoding utf8 -NoNewline
    @"
generated_by: deltafuse@$FrameworkVersion
source: deltafuse://v$FrameworkVersion/skills/$SkillName
content_hash: sha256:$ContentHash
"@ | Set-Content -LiteralPath (Join-Path $Destination ".deltafuse-generated.yaml") -Encoding utf8 -NoNewline
}

function Install-GeneratedSkills {
    param([string]$AdapterRootRelative, [string]$ContentHash, [string]$Mode, [string]$NestedRel)

    $adapterRoot = Join-Path $TargetRoot $AdapterRootRelative
    New-Item -ItemType Directory -Path $adapterRoot -Force | Out-Null
    $actualMode = $Mode
    $skillDirectories = @(Get-ChildItem -LiteralPath (Join-Path $FrameworkRoot "process/skills") -Directory)

    if ($Mode -eq "link") {
        $probe = Join-Path $adapterRoot ".deltafuse-link-probe"
        if (-not (New-DirLink $probe $skillDirectories[0].FullName)) {
            $actualMode = "copy"
        }
        if (Test-Path -LiteralPath $probe) {
            Remove-SkillSlot $probe
        }
    }

    foreach ($skillDirectory in $skillDirectories) {
        $skillName = $skillDirectory.Name
        $destination = Join-Path $adapterRoot $skillName
        if (Test-Path -LiteralPath $destination) {
            if (-not (Test-GeneratedSkillSlot $destination)) {
                Write-Warning "Preserving non-generated skill: $AdapterRootRelative/$skillName"
                continue
            }
            Remove-SkillSlot $destination
        }
        if ($actualMode -eq "link") {
            if (-not (New-DirLink $destination $skillDirectory.FullName)) {
                $actualMode = "copy"
                Install-SkillCopy $skillDirectory.FullName $destination $skillName $ContentHash
            }
        } else {
            Install-SkillCopy $skillDirectory.FullName $destination $skillName $ContentHash
        }
    }

    $adapterMarker = Join-Path $adapterRoot ".deltafuse-generated.yaml"
    if ($actualMode -eq "link" -and $NestedRel) {
        @"
generated_by: deltafuse@$FrameworkVersion
mode: link
source: $NestedRel
content_hash: sha256:$ContentHash
"@ | Set-Content -LiteralPath $adapterMarker -Encoding utf8 -NoNewline
    } elseif (Test-Path -LiteralPath $adapterMarker) {
        $markerText = Get-Content -LiteralPath $adapterMarker -Raw
        if ($markerText -match 'mode:\s*link') {
            Remove-Item -LiteralPath $adapterMarker -Force
        }
    }
    return $actualMode
}

Write-Host "Installing DeltaFuse $FrameworkVersion into $TargetRoot..." -ForegroundColor Cyan
New-Item -ItemType Directory -Path $TargetRoot -Force | Out-Null

$FrameworkHash = Get-FrameworkContentHash
$configPath = Join-Path $TargetRoot ".deltafuse/config.yaml"
$configExisted = Test-Path -LiteralPath $configPath
$lockPath = Join-Path $TargetRoot ".deltafuse/lock.yaml"
if ((Test-Path -LiteralPath $lockPath) -and -not $Force) {
    $existingLock = Get-Content -LiteralPath $lockPath -Raw
    if ($existingLock -notmatch [regex]::Escape("content_hash: sha256:$FrameworkHash")) {
        throw "A different DeltaFuse lock already exists. Rerun with -Force for an explicit upgrade."
    }
}

$directories = @(
    ".deltafuse",
    "docs/intake",
    "docs/changes",
    "docs/spec",
    "docs/decisions",
    "docs/archive/intake",
    "docs/archive/changes"
)
foreach ($directory in $directories) {
    New-Item -ItemType Directory -Path (Join-Path $TargetRoot $directory) -Force | Out-Null
}

Copy-TemplateFile "process/templates/AGENTS.md" "AGENTS.md"
Copy-TemplateFile "process/templates/.deltafuse/config.yaml" ".deltafuse/config.yaml"
Copy-TemplateFile "process/templates/docs/intake/README.md" "docs/intake/README.md"
Copy-TemplateFile "process/templates/docs/changes/README.md" "docs/changes/README.md"
Copy-TemplateFile "process/templates/docs/spec/README.md" "docs/spec/README.md"
Copy-TemplateFile "process/templates/docs/spec/context.md" "docs/spec/context.md"
Copy-TemplateFile "process/templates/docs/spec/_capabilities.yaml" "docs/spec/_capabilities.yaml"
Copy-TemplateFile "process/templates/docs/decisions/README.md" "docs/decisions/README.md"
Copy-TemplateFile "process/templates/docs/decisions/DEC-0000-template.md" "docs/decisions/DEC-0000-template.md"
Copy-TemplateFile "process/templates/docs/archive/README.md" "docs/archive/README.md"
Copy-TemplateFile "process/templates/docs/archive/intake/README.md" "docs/archive/intake/README.md"
Copy-TemplateFile "process/templates/docs/archive/changes/README.md" "docs/archive/changes/README.md"
Copy-TemplateFile "process/templates/CHANGELOG.md" "CHANGELOG.md"

$configSource = $null
$adapterModeRequested = "auto"
if (Test-Path -LiteralPath $configPath) {
    $configRaw = Get-Content -LiteralPath $configPath -Raw
    $sourceMatch = [regex]::Match($configRaw, "(?m)^\s{2}source:\s*(\S+)\s*$")
    if ($sourceMatch.Success) {
        $configSource = $sourceMatch.Groups[1].Value
    }
    $modeMatch = [regex]::Match($configRaw, "(?m)^\s{2}mode:\s*(\S+)\s*$")
    if ($modeMatch.Success) {
        $adapterModeRequested = $modeMatch.Groups[1].Value.Trim().ToLowerInvariant()
    }
}
if ($adapterModeRequested -notin @("auto", "link", "copy")) {
    throw "Invalid .deltafuse/config.yaml adapters.mode: $adapterModeRequested"
}

$nestedRel = Get-NestedFrameworkRel
$adapterMode = if ($adapterModeRequested -eq "copy") {
    "copy"
} elseif ($adapterModeRequested -eq "link") {
    if (-not $nestedRel) {
        throw "adapters.mode is link but the framework checkout is not inside the product (use a git submodule or vendor path, or set adapters.mode to copy)."
    }
    "link"
} elseif ($nestedRel) {
    "link"
} else {
    "copy"
}

$effectiveSource = if ($adapterMode -eq "link" -and $nestedRel) {
    $nestedRel
} elseif ($configSource -and $configSource -ne "deltafuse" -and -not $configSource.StartsWith("deltafuse://")) {
    $configSource
} else {
    "deltafuse://v$FrameworkVersion"
}

if (Test-Path -LiteralPath $configPath) {
    $configContent = Get-Content -LiteralPath $configPath -Raw
    $dirty = $false
    if (-not $configExisted -or $Force) {
        if ($configContent -notmatch "(?m)^\s{2}version:\s*\S+\s*$") {
            throw "Cannot update framework version: .deltafuse/config.yaml has no indented version field."
        }
        $configContent = [regex]::Replace($configContent, "(?m)^(\s{2}version:\s*)\S+(\s*)$", "`${1}$FrameworkVersion`${2}", 1)
        $dirty = $true
    }
    if ($adapterMode -eq "link" -or (-not $configExisted -or $Force)) {
        $configContent = [regex]::Replace($configContent, "(?m)^(\s{2}source:\s*)\S+(\s*)$", "`${1}$effectiveSource`${2}", 1)
        $dirty = $true
    }
    if ($dirty) {
        Set-Content -LiteralPath $configPath -Value $configContent -Encoding utf8 -NoNewline
    }
}

$callWidth = "wide"
$autoAccept = "false"
if (Test-Path -LiteralPath $configPath) {
    $cfgText = Get-Content -LiteralPath $configPath -Raw
    if ($cfgText -match '(?m)^\s+call_width:\s+(\S+)\s*$') {
        $extractedWidth = $Matches[1].Trim()
        if ($extractedWidth -notin @("narrow", "medium", "wide")) {
            throw "Invalid .deltafuse/config.yaml workflow.call_width: $extractedWidth"
        }
        $callWidth = $extractedWidth
    }
    if ($cfgText -match '(?m)^\s+auto_accept_decisions:\s+(true|false)\s*$') {
        $autoAccept = $Matches[1]
    }
}

@"
schema_version: $SchemaVersion
framework:
  version: $FrameworkVersion
  source: $effectiveSource
  content_hash: sha256:$FrameworkHash
workflow:
  call_width: $callWidth
  auto_accept_decisions: $autoAccept
"@ | Set-Content -LiteralPath $lockPath -Encoding utf8 -NoNewline

$adapterRoots = @()
if (Test-Path -LiteralPath $configPath) {
    $configLines = Get-Content -LiteralPath $configPath
    $inAdapters = $false
    $inRoots = $false
    foreach ($line in $configLines) {
        if ($line -match "^adapters:\s*$") { $inAdapters = $true; continue }
        if ($inAdapters -and $line -match "^\s+roots:\s*$") { $inRoots = $true; continue }
        if ($inRoots) {
            if ($line -match "^\s+-\s*(.+)\s*$") {
                $adapterRoots += $Matches[1].Trim()
            } elseif ($line -match "^\S" -or ($line -match "^\s+\S" -and $line -notmatch "^\s+roots:")) {
                $inAdapters = $false
                $inRoots = $false
            }
        }
    }
}
if ($adapterRoots.Count -eq 0) {
    $adapterRoots = @(".agents/skills", ".cursor/skills", ".gemini/skills")
}

foreach ($root in $adapterRoots) {
    $used = Install-GeneratedSkills $root $FrameworkHash $adapterMode $nestedRel
    if ($used -ne "link") {
        $adapterMode = "copy"
    }
}

if ($adapterModeRequested -eq "link" -and $adapterMode -ne "link") {
    throw "Could not create skill symlinks. On Windows enable Developer Mode, or set adapters.mode to copy."
}

if ($adapterMode -eq "copy" -and $nestedRel -and $effectiveSource -eq $nestedRel) {
    $effectiveSource = "deltafuse://v$FrameworkVersion"
    if (Test-Path -LiteralPath $configPath) {
        $configContent = Get-Content -LiteralPath $configPath -Raw
        $configContent = [regex]::Replace($configContent, "(?m)^(\s{2}source:\s*)\S+(\s*)$", "`${1}$effectiveSource`${2}", 1)
        Set-Content -LiteralPath $configPath -Value $configContent -Encoding utf8 -NoNewline
    }
    @"
schema_version: $SchemaVersion
framework:
  version: $FrameworkVersion
  source: $effectiveSource
  content_hash: sha256:$FrameworkHash
workflow:
  call_width: $callWidth
  auto_accept_decisions: $autoAccept
"@ | Set-Content -LiteralPath $lockPath -Encoding utf8 -NoNewline
}

Write-Host "DeltaFuse installed. Canonical process remains external; product state is under docs/." -ForegroundColor Green
if ($adapterMode -eq "link") {
    Write-Host "Adapter skills are relative links into the nested framework checkout." -ForegroundColor Green
}
