#!/usr/bin/env bash
# DeltaFuse v2 product installer
set -euo pipefail

TARGET_DIR="."
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    *) TARGET_DIR="$arg" ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_ROOT="$(mkdir -p "$TARGET_DIR" && cd "$TARGET_DIR" && pwd)"
FRAMEWORK_VERSION="$(tr -d '\r\n' < "$SCRIPT_DIR/VERSION")"
SCHEMA_VERSION=2

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

framework_hash() {
  local manifest result
  manifest="$(mktemp)"
  {
    for root in docs process scripts tests src; do
      if [ -d "$SCRIPT_DIR/$root" ]; then
        # Must stay in sync with src/deltafuse/core/hasher.py: skip transient caches
        find "$SCRIPT_DIR/$root" -type f -print | grep -Ev '/(__pycache__|\.pytest_cache)/' || true
      fi
    done
    printf '%s\n' "$SCRIPT_DIR/VERSION"
    # DF3-003 / SEC-02: entrypoints (pyproject.toml scripts table) are pinned too
    printf '%s\n' "$SCRIPT_DIR/pyproject.toml"
  } | while IFS= read -r file; do
    relative="$(printf '%s' "${file#"$SCRIPT_DIR/"}" | tr '[:upper:]' '[:lower:]')"
    printf '%s:%s\n' "$relative" "$(sha256_file "$file")"
  done | LC_ALL=C sort > "$manifest"
  result="$(sha256_file "$manifest")"
  rm -f -- "$manifest"
  printf '%s\n' "$result"
}

copy_template() {
  local source_relative="$1"
  local target_relative="$2"
  local target="$TARGET_ROOT/$target_relative"
  mkdir -p "$(dirname "$target")"
  if [ -e "$target" ]; then
    printf 'Preserving existing %s\n' "$target_relative"
    return
  fi
  cp "$SCRIPT_DIR/$source_relative" "$target"
}

HOOK_MARKER='Generated by DeltaFuse installer. DO NOT EDIT.'
HOOK_SCRIPT=$(cat <<'EOF'
#!/bin/sh
# Generated by DeltaFuse installer. DO NOT EDIT.
root=$(git rev-parse --show-toplevel) || exit 1
cd "$root" || exit 1
py="${DELTAFUSE_PYTHON:-python}"
exec "$py" -m deltafuse leash "$root"
EOF
)

remove_marked_hook() {
  local path="$1"
  if [ -f "$path" ] && grep -F -q "$HOOK_MARKER" "$path"; then
    rm -f "$path"
  fi
}

sync_leash_hook() {
  local mode="$1"
  local managed="$TARGET_ROOT/.deltafuse/hooks/pre-commit"
  local git_hook="$TARGET_ROOT/.git/hooks/pre-commit"
  case "$mode" in
    off|'')
      remove_marked_hook "$managed"
      remove_marked_hook "$git_hook"
      return
      ;;
  esac
  mkdir -p "$(dirname "$managed")"
  printf '%s\n' "$HOOK_SCRIPT" > "$managed"
  chmod +x "$managed" 2>/dev/null || true
  if [ ! -d "$TARGET_ROOT/.git" ]; then
    return
  fi
  if [ -f "$git_hook" ] && ! grep -F -q "$HOOK_MARKER" "$git_hook"; then
    return
  fi
  mkdir -p "$(dirname "$git_hook")"
  printf '%s\n' "$HOOK_SCRIPT" > "$git_hook"
  chmod +x "$git_hook" 2>/dev/null || true
}

nested_framework_rel() {
  local fw tgt
  fw="$(cd "$SCRIPT_DIR" && pwd)"
  tgt="$TARGET_ROOT"
  if [ "$fw" = "$tgt" ]; then
    printf '.\n'
    return 0
  fi
  case "$fw" in
    "$tgt"/*)
      printf '%s\n' "${fw#"$tgt"/}"
      return 0
      ;;
  esac
  return 1
}

adapter_relpath() {
  local from="$1"
  local to="$2"
  local python
  python="$(command -v python3 || command -v python || true)"
  if [ -n "$python" ]; then
    "$python" -c 'import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "$to" "$from"
    return 0
  fi
  return 1
}

install_skill_copy() {
  local source="$1"
  local destination="$2"
  local skill_name="$3"
  local content_hash="$4"
  cp -R "$source" "$destination"
  local skill_file="$destination/SKILL.md"
  local temporary
  temporary="$(mktemp)"
  awk -v version="$FRAMEWORK_VERSION" -v name="$skill_name" -v hash="$content_hash" '
    NR == 1 && $0 == "---" {
      print
      print "# DO NOT EDIT: generated by DeltaFuse installer."
      print "# deltafuse-version: " version
      print "# deltafuse-source: deltafuse://v" version "/skills/" name
      print "# deltafuse-content-hash: sha256:" hash
      next
    }
    { print }
  ' "$skill_file" > "$temporary"
  mv "$temporary" "$skill_file"
  cat > "$destination/.deltafuse-generated.yaml" <<EOF
generated_by: deltafuse@$FRAMEWORK_VERSION
source: deltafuse://v$FRAMEWORK_VERSION/skills/$skill_name
content_hash: sha256:$content_hash
EOF
}

install_generated_skills() {
  local adapter_relative="$1"
  local content_hash="$2"
  local mode="$3"
  local nested_rel="$4"
  local adapter_root="$TARGET_ROOT/$adapter_relative"
  local actual_mode="$mode"
  mkdir -p "$adapter_root"

  if [ "$mode" = "link" ]; then
    local probe="$adapter_root/.deltafuse-link-probe"
    local sample
    sample="$(printf '%s\n' "$SCRIPT_DIR"/process/skills/* | head -n 1)"
    rel="$(adapter_relpath "$adapter_root" "$sample" || true)"
    if [ -z "$rel" ] || ! ln -sfn "$rel" "$probe" 2>/dev/null; then
      actual_mode="copy"
    fi
    rm -rf -- "$probe"
  fi

  for source in "$SCRIPT_DIR"/process/skills/*; do
    [ -d "$source" ] || continue
    skill_name="$(basename "$source")"
    destination="$adapter_root/$skill_name"
    marker="$destination/.deltafuse-generated.yaml"

    if [ -e "$destination" ] || [ -L "$destination" ]; then
      if [ ! -L "$destination" ] && [ ! -f "$marker" ]; then
        printf 'WARNING: preserving non-generated skill %s/%s\n' "$adapter_relative" "$skill_name" >&2
        continue
      fi
      rm -rf -- "$destination"
    fi

    if [ "$actual_mode" = "link" ]; then
      rel="$(adapter_relpath "$adapter_root" "$source" || true)"
      if [ -z "$rel" ] || ! ln -sfn "$rel" "$destination" 2>/dev/null; then
        actual_mode="copy"
        install_skill_copy "$source" "$destination" "$skill_name" "$content_hash"
      fi
    else
      install_skill_copy "$source" "$destination" "$skill_name" "$content_hash"
    fi
  done

  adapter_marker="$adapter_root/.deltafuse-generated.yaml"
  if [ "$actual_mode" = "link" ] && [ -n "$nested_rel" ]; then
    cat > "$adapter_marker" <<EOF
generated_by: deltafuse@$FRAMEWORK_VERSION
mode: link
source: $nested_rel
content_hash: sha256:$content_hash
EOF
  elif [ -f "$adapter_marker" ] && grep -Fq 'mode: link' "$adapter_marker"; then
    rm -f -- "$adapter_marker"
  fi
  printf '%s\n' "$actual_mode"
}

printf 'Installing DeltaFuse %s into %s...\n' "$FRAMEWORK_VERSION" "$TARGET_ROOT"
FRAMEWORK_HASH="$(framework_hash)"
LOCK_PATH="$TARGET_ROOT/.deltafuse/lock.yaml"

if [ -f "$LOCK_PATH" ] && [ "$FORCE" -ne 1 ] && ! grep -Fq "content_hash: sha256:$FRAMEWORK_HASH" "$LOCK_PATH"; then
  printf 'A different DeltaFuse lock already exists. Rerun with --force for an explicit upgrade.\n' >&2
  exit 1
fi

mkdir -p \
  "$TARGET_ROOT/.deltafuse" \
  "$TARGET_ROOT/docs/intake" \
  "$TARGET_ROOT/docs/changes" \
  "$TARGET_ROOT/docs/spec" \
  "$TARGET_ROOT/docs/decisions" \
  "$TARGET_ROOT/docs/archive/intake" \
  "$TARGET_ROOT/docs/archive/changes"

config_existed=0
if [ -f "$TARGET_ROOT/.deltafuse/config.yaml" ]; then
  config_existed=1
fi

copy_template process/templates/AGENTS.md AGENTS.md
copy_template process/templates/.deltafuse/config.yaml .deltafuse/config.yaml
copy_template process/templates/docs/intake/README.md docs/intake/README.md
copy_template process/templates/docs/changes/README.md docs/changes/README.md
copy_template process/templates/docs/spec/README.md docs/spec/README.md
copy_template process/templates/docs/spec/context.md docs/spec/context.md
copy_template process/templates/docs/spec/_capabilities.yaml docs/spec/_capabilities.yaml
copy_template process/templates/docs/decisions/README.md docs/decisions/README.md
copy_template process/templates/docs/decisions/DEC-0000-template.md docs/decisions/DEC-0000-template.md
copy_template process/templates/docs/archive/README.md docs/archive/README.md
copy_template process/templates/docs/archive/intake/README.md docs/archive/intake/README.md
copy_template process/templates/docs/archive/changes/README.md docs/archive/changes/README.md
copy_template process/templates/CHANGELOG.md CHANGELOG.md
copy_template process/templates/.github/workflows/deltafuse-leash.yml .github/workflows/deltafuse-leash.yml

config_file="$TARGET_ROOT/.deltafuse/config.yaml"
config_source=""
adapter_mode_requested="auto"
if [ -f "$config_file" ]; then
  config_source="$(awk '/^  source:[[:space:]]*/ { sub(/^  source:[[:space:]]*/, ""); sub(/[[:space:]]+$/, ""); print; exit }' "$config_file")"
  extracted_mode="$(awk '
    /^adapters:[[:space:]]*$/ { in_ad=1; next }
    in_ad && /^[^[:space:]]/ { in_ad=0 }
    in_ad && /^[[:space:]]+mode:[[:space:]]+/ {
      sub(/^[[:space:]]+mode:[[:space:]]+/, "")
      sub(/[[:space:]]+$/, "")
      print
      exit
    }
  ' "$config_file")"
  if [ -n "$extracted_mode" ]; then
    adapter_mode_requested="$extracted_mode"
  fi
fi

case "$adapter_mode_requested" in
  auto|link|copy) ;;
  *)
    printf 'Invalid .deltafuse/config.yaml adapters.mode: %s\n' "$adapter_mode_requested" >&2
    exit 1
    ;;
esac

nested_rel=""
if nested_rel="$(nested_framework_rel)"; then
  :
else
  nested_rel=""
fi

adapter_mode="copy"
if [ "$adapter_mode_requested" = "copy" ]; then
  adapter_mode="copy"
elif [ "$adapter_mode_requested" = "link" ]; then
  if [ -z "$nested_rel" ]; then
    printf 'adapters.mode is link but the framework checkout is not inside the product (use a git submodule or vendor path, or set adapters.mode to copy).\n' >&2
    exit 1
  fi
  adapter_mode="link"
elif [ -n "$nested_rel" ]; then
  adapter_mode="link"
fi

effective_source="deltafuse://v$FRAMEWORK_VERSION"
if [ "$adapter_mode" = "link" ] && [ -n "$nested_rel" ]; then
  effective_source="$nested_rel"
elif [ -n "$config_source" ] && [ "$config_source" != "deltafuse" ] && [[ ! "$config_source" =~ ^deltafuse:// ]]; then
  effective_source="$config_source"
fi

update_ver=0
update_src=0
if [ "$config_existed" -eq 0 ] || [ "$FORCE" -eq 1 ]; then
  update_ver=1
  update_src=1
fi
if [ "$adapter_mode" = "link" ]; then
  update_src=1
fi

if [ -f "$config_file" ] && { [ "$update_ver" -eq 1 ] || [ "$update_src" -eq 1 ]; }; then
  temporary="$(mktemp)"
  awk -v version="$FRAMEWORK_VERSION" -v source="$effective_source" -v do_ver="$update_ver" -v do_src="$update_src" '
    do_ver == 1 && !updated_ver && /^  version:[[:space:]]*/ {
      print "  version: " version
      updated_ver=1
      next
    }
    do_src == 1 && !updated_src && /^  source:[[:space:]]*/ {
      print "  source: " source
      updated_src=1
      next
    }
    { print }
    END { if (do_ver == 1 && !updated_ver) exit 42 }
  ' "$config_file" > "$temporary" || {
    status=$?
    rm -f -- "$temporary"
    if [ "$status" -eq 42 ]; then
      printf 'Cannot update framework version: .deltafuse/config.yaml has no indented version field.\n' >&2
    fi
    exit "$status"
  }
  mv "$temporary" "$config_file"
fi

call_width="wide"
auto_accept="false"
leash_mode="off"
if [ -f "$config_file" ]; then
  extracted_width="$(awk '
    /^workflow:[[:space:]]*$/ { in_wf=1; next }
    in_wf && /^[^[:space:]]/ { in_wf=0 }
    in_wf && /^[[:space:]]+call_width:[[:space:]]+/ {
      sub(/^[[:space:]]+call_width:[[:space:]]+/, "")
      sub(/[[:space:]]+$/, "")
      print
      exit
    }
  ' "$config_file")"
  if [ -n "$extracted_width" ]; then
    case "$extracted_width" in
      narrow|medium|wide) call_width="$extracted_width" ;;
      *)
        printf 'Invalid .deltafuse/config.yaml workflow.call_width: %s\n' "$extracted_width" >&2
        exit 1
        ;;
    esac
  fi
  extracted_auto="$(awk '
    /^workflow:[[:space:]]*$/ { in_wf=1; next }
    in_wf && /^[^[:space:]]/ { in_wf=0 }
    in_wf && /^[[:space:]]+auto_accept_decisions:[[:space:]]+/ {
      sub(/^[[:space:]]+auto_accept_decisions:[[:space:]]+/, "")
      sub(/[[:space:]]+$/, "")
      print
      exit
    }
  ' "$config_file")"
  if [ -n "$extracted_auto" ]; then
    case "$extracted_auto" in
      true|false) auto_accept="$extracted_auto" ;;
      *)
        printf 'Invalid .deltafuse/config.yaml workflow.auto_accept_decisions: %s\n' "$extracted_auto" >&2
        exit 1
        ;;
    esac
  fi
  extracted_leash="$(awk '
    /^workflow:[[:space:]]*$/ { in_wf=1; next }
    in_wf && /^[^[:space:]]/ { in_wf=0 }
    in_wf && /^[[:space:]]+leash:[[:space:]]+/ {
      sub(/^[[:space:]]+leash:[[:space:]]+/, "")
      sub(/[[:space:]]+$/, "")
      print
      exit
    }
  ' "$config_file")"
  if [ -n "$extracted_leash" ]; then
    extracted_leash="${extracted_leash#\"}"
    extracted_leash="${extracted_leash%\"}"
    extracted_leash="${extracted_leash#\'}"
    extracted_leash="${extracted_leash%\'}"
    case "$extracted_leash" in
      off|advisory|enforce) leash_mode="$extracted_leash" ;;
      *)
        printf 'Invalid .deltafuse/config.yaml workflow.leash: %s\n' "$extracted_leash" >&2
        exit 1
        ;;
    esac
  fi
fi

cat > "$LOCK_PATH" <<EOF
schema_version: $SCHEMA_VERSION
framework:
  version: $FRAMEWORK_VERSION
  source: $effective_source
  content_hash: sha256:$FRAMEWORK_HASH
workflow:
  call_width: $call_width
  auto_accept_decisions: $auto_accept
EOF

adapter_roots=()
if [ -f "$config_file" ]; then
  while IFS= read -r root; do
    [ -n "$root" ] && adapter_roots+=("$root")
  done < <(awk '
    /^adapters:[[:space:]]*$/ { in_adapters=1; next }
    in_adapters && /^[[:space:]]+roots:[[:space:]]*$/ { in_roots=1; next }
    in_roots && /^[[:space:]]+-[[:space:]]+/ {
      sub(/^[[:space:]]+-[[:space:]]+/, "")
      sub(/[[:space:]]+$/, "")
      print
      next
    }
    in_roots && /^[^[:space:]]/ { in_adapters=0; in_roots=0 }
  ' "$config_file")
fi

if [ ${#adapter_roots[@]} -eq 0 ]; then
  adapter_roots=(.agents/skills .cursor/skills .gemini/skills)
fi

actual_mode="$adapter_mode"
for root in "${adapter_roots[@]}"; do
  used="$(install_generated_skills "$root" "$FRAMEWORK_HASH" "$adapter_mode" "$nested_rel")"
  if [ "$used" != "link" ]; then
    actual_mode="copy"
  fi
done

if [ "$adapter_mode_requested" = "link" ] && [ "$actual_mode" != "link" ]; then
  printf 'Could not create skill symlinks. On Windows enable Developer Mode, or set adapters.mode to copy.\n' >&2
  exit 1
fi

if [ "$actual_mode" = "copy" ] && [ -n "$nested_rel" ] && [ "$effective_source" = "$nested_rel" ]; then
  effective_source="deltafuse://v$FRAMEWORK_VERSION"
  if [ -f "$config_file" ]; then
    temporary="$(mktemp)"
    awk -v source="$effective_source" '
      !updated_src && /^  source:[[:space:]]*/ { print "  source: " source; updated_src=1; next }
      { print }
    ' "$config_file" > "$temporary"
    mv "$temporary" "$config_file"
  fi
  cat > "$LOCK_PATH" <<EOF
schema_version: $SCHEMA_VERSION
framework:
  version: $FRAMEWORK_VERSION
  source: $effective_source
  content_hash: sha256:$FRAMEWORK_HASH
workflow:
  call_width: $call_width
  auto_accept_decisions: $auto_accept
EOF
fi

sync_leash_hook "$leash_mode"

printf 'DeltaFuse installed. Canonical process remains external; product state is under docs/.\n'
if [ "$actual_mode" = "link" ]; then
  printf 'Adapter skills are relative links into the nested framework checkout.\n'
fi
