"""Adapter skill install: stamped copies, or relative links into a nested checkout."""

from __future__ import annotations

import os
import re
import shutil
from pathlib import Path
from typing import Any

import yaml

ADAPTER_MODES = frozenset({"auto", "link", "copy"})
DEFAULT_ADAPTER_MODE = "auto"
ADAPTER_MARKER_NAME = ".deltafuse-generated.yaml"
_WINDOWS_REPARSE_POINT = 0x400


def is_framework_uri(source: str | None) -> bool:
    if not source:
        return True
    text = str(source).strip()
    return text == "deltafuse" or text.startswith("deltafuse://")


def adapter_mode_from_mapping(data: dict[str, Any] | None) -> tuple[str, list[str]]:
    """Return (mode, errors) from product config."""
    if not isinstance(data, dict):
        return DEFAULT_ADAPTER_MODE, []
    adapters = data.get("adapters")
    if not isinstance(adapters, dict) or "mode" not in adapters:
        return DEFAULT_ADAPTER_MODE, []
    raw = adapters.get("mode")
    mode = str(raw).strip().lower() if raw is not None else DEFAULT_ADAPTER_MODE
    if mode not in ADAPTER_MODES:
        return DEFAULT_ADAPTER_MODE, [
            f"adapters.mode must be one of {', '.join(sorted(ADAPTER_MODES))}; got {raw!r}"
        ]
    return mode, []


def nested_framework_relposix(framework_root: Path, target_root: Path) -> str | None:
    """Posix path of the framework inside the product, or None if it is not nested.

    Uses abspath (does not follow the checkout symlink) so a vendored symlink
    still counts as nested.
    """
    fw = os.path.abspath(framework_root)
    tgt = os.path.abspath(target_root)
    try:
        rel = os.path.relpath(fw, tgt)
    except ValueError:
        return None
    rel_posix = Path(rel).as_posix()
    if rel_posix == ".":
        return "."
    if rel_posix == ".." or rel_posix.startswith("../"):
        return None
    return rel_posix


def resolve_effective_adapter_mode(
    requested: str, framework_root: Path, target_root: Path
) -> tuple[str, str | None]:
    """Return ('link', nested_rel) or ('copy', None)."""
    nested = nested_framework_relposix(framework_root, target_root)
    if requested == "copy":
        return "copy", None
    if requested == "link":
        return "link", nested
    if nested:
        return "link", nested
    return "copy", None


def is_link_path(path: Path) -> bool:
    if path.is_symlink():
        return True
    if os.name != "nt":
        return False
    try:
        attrs = getattr(path.lstat(), "st_file_attributes", 0)
        return bool(attrs & _WINDOWS_REPARSE_POINT)
    except OSError:
        return False


def _remove_skill_slot(dest: Path) -> None:
    if dest.is_symlink() or is_link_path(dest):
        dest.unlink()
        return
    if dest.is_dir():
        shutil.rmtree(dest)
        return
    if dest.exists():
        dest.unlink()


def _is_generated_slot(dest: Path) -> bool:
    if dest.is_symlink() or is_link_path(dest):
        return True
    return dest.is_dir() and (dest / ADAPTER_MARKER_NAME).is_file()


def try_relative_dir_symlink(link: Path, target: Path) -> bool:
    """Create a relative directory symlink, or a Windows junction if symlinks are denied."""
    link.parent.mkdir(parents=True, exist_ok=True)
    rel = os.path.relpath(target, start=link.parent)
    try:
        link.symlink_to(rel, target_is_directory=True)
        return True
    except OSError:
        if os.name != "nt":
            return False
        return _try_windows_junction(link, target)


def _try_windows_junction(link: Path, target: Path) -> bool:
    """Local-only fallback. Junctions are absolute; do not commit them."""
    import subprocess

    completed = subprocess.run(
        ["cmd", "/c", "mklink", "/J", os.path.abspath(link), os.path.abspath(target)],
        capture_output=True,
        text=True,
    )
    return completed.returncode == 0


def _can_symlink_dirs(adapter_root: Path, sample_target: Path) -> bool:
    probe = adapter_root / f".deltafuse-link-probe-{os.getpid()}"
    try:
        if not try_relative_dir_symlink(probe, sample_target):
            return False
        return is_link_path(probe)
    finally:
        if probe.exists() or probe.is_symlink():
            _remove_skill_slot(probe)


def _copy_skill(
    skill_dir: Path,
    dest: Path,
    version: str,
    content_hash: str,
    skill_name: str,
) -> None:
    shutil.copytree(skill_dir, dest)
    skill_md = dest / "SKILL.md"
    if skill_md.is_file():
        content = skill_md.read_text(encoding="utf-8")
        banner = (
            f"---\n"
            f"# DO NOT EDIT: generated by DeltaFuse installer.\n"
            f"# deltafuse-version: {version}\n"
            f"# deltafuse-source: deltafuse://v{version}/skills/{skill_name}\n"
            f"# deltafuse-content-hash: sha256:{content_hash}\n"
        )
        content = re.sub(r"\A---\r?\n", banner, content)
        skill_md.write_text(content, encoding="utf-8")
    marker = dest / ADAPTER_MARKER_NAME
    marker.write_text(
        f"generated_by: deltafuse@{version}\n"
        f"source: deltafuse://v{version}/skills/{skill_name}\n"
        f"content_hash: sha256:{content_hash}\n",
        encoding="utf-8",
    )


def _write_adapter_link_marker(
    adapter_root: Path, version: str, nested_relposix: str, content_hash: str
) -> None:
    (adapter_root / ADAPTER_MARKER_NAME).write_text(
        f"generated_by: deltafuse@{version}\n"
        f"mode: link\n"
        f"source: {nested_relposix}\n"
        f"content_hash: sha256:{content_hash}\n",
        encoding="utf-8",
    )


def _skill_dirs(skills_src: Path) -> list[Path]:
    return sorted((p for p in skills_src.iterdir() if p.is_dir()), key=lambda p: p.name)


def install_adapter_skills(
    *,
    framework_root: Path,
    target_root: Path,
    adapter_rel: str,
    version: str,
    content_hash: str,
    mode: str,
    nested_relposix: str | None,
) -> tuple[int, str]:
    """Install one adapter root. Returns (count, actual_mode); actual_mode may fall back to copy."""
    adapter_root = target_root / adapter_rel
    adapter_root.mkdir(parents=True, exist_ok=True)
    skills_src = framework_root / "process" / "skills"
    if not skills_src.is_dir():
        return 0, mode

    dirs = _skill_dirs(skills_src)
    if not dirs:
        return 0, mode

    actual_mode = mode
    if mode == "link" and (not nested_relposix or not _can_symlink_dirs(adapter_root, dirs[0])):
        actual_mode = "copy"

    generated: list[tuple[Path, Path]] = []
    for skill_dir in dirs:
        dest = adapter_root / skill_dir.name
        if dest.exists() or dest.is_symlink():
            if not _is_generated_slot(dest):
                continue
            _remove_skill_slot(dest)
        generated.append((skill_dir, dest))

    if actual_mode == "link":
        linked = True
        for skill_dir, dest in generated:
            if not try_relative_dir_symlink(dest, skill_dir):
                linked = False
                break
        if linked and generated and nested_relposix:
            _write_adapter_link_marker(adapter_root, version, nested_relposix, content_hash)
            return len(generated), "link"
        for _, dest in generated:
            if dest.exists() or dest.is_symlink():
                _remove_skill_slot(dest)
        actual_mode = "copy"

    for skill_dir, dest in generated:
        if dest.exists() or dest.is_symlink():
            _remove_skill_slot(dest)
        _copy_skill(skill_dir, dest, version, content_hash, skill_dir.name)

    adapter_marker = adapter_root / ADAPTER_MARKER_NAME
    if adapter_marker.is_file():
        text = adapter_marker.read_text(encoding="utf-8", errors="ignore")
        if "mode: link" in text:
            adapter_marker.unlink()

    return len(generated), actual_mode


def validate_adapter_skills(
    product_root: Path,
    adapter_rel: str,
    skill_names: list[str],
    *,
    lock_version: str | None,
    lock_hash: str | None,
    lock_source: str | None,
) -> list[str]:
    """Layout errors for one adapter root (copy stamps or nested links)."""
    errors: list[str] = []
    adapter_path = product_root / adapter_rel
    if not adapter_path.is_dir():
        errors.append(f"Missing configured adapter root: {adapter_rel}")
        return errors

    adapter_marker = adapter_path / ADAPTER_MARKER_NAME
    link_mode = False
    marker_source: str | None = None
    marker_text = ""
    if adapter_marker.is_file():
        marker_text = adapter_marker.read_text(encoding="utf-8", errors="ignore")
        try:
            loaded = yaml.safe_load(marker_text) or {}
        except Exception:
            loaded = {}
        if isinstance(loaded, dict) and str(loaded.get("mode", "")).strip() == "link":
            link_mode = True
            raw_source = loaded.get("source")
            if raw_source:
                marker_source = str(raw_source).strip()

    if link_mode:
        fw_rel = marker_source or (None if is_framework_uri(lock_source) else lock_source)
        if not fw_rel:
            errors.append(f"Linked adapter {adapter_rel} has no nested framework source")
            return errors
        fw_root = (product_root / fw_rel).resolve()
        if not (fw_root / "process" / "skills").is_dir():
            errors.append(
                f"Linked adapter {adapter_rel} source '{fw_rel}' is not a DeltaFuse checkout"
            )
            return errors
        if lock_version and f"generated_by: deltafuse@{lock_version}" not in marker_text:
            errors.append(f"Generated adapter version mismatch: {adapter_rel}")
        if lock_hash and f"content_hash: {lock_hash}" not in marker_text:
            errors.append(f"Generated adapter hash mismatch: {adapter_rel}")
        for skill in skill_names:
            skill_dir = adapter_path / skill
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.is_file():
                errors.append(f"Missing generated skill: {adapter_rel}/{skill}/SKILL.md")
                continue
            if not is_link_path(skill_dir):
                errors.append(f"Generated skill is not a symlink: {adapter_rel}/{skill}")
                continue
            expected = (fw_root / "process" / "skills" / skill).resolve()
            try:
                actual = skill_dir.resolve()
            except OSError:
                errors.append(f"Generated skill symlink is broken: {adapter_rel}/{skill}")
                continue
            if actual != expected:
                errors.append(
                    f"Generated skill symlink does not point at {fw_rel}/process/skills/{skill}: {adapter_rel}/{skill}"
                )
        return errors

    for skill in skill_names:
        skill_dir = adapter_path / skill
        skill_md = skill_dir / "SKILL.md"
        marker = skill_dir / ADAPTER_MARKER_NAME
        if not skill_md.is_file():
            errors.append(f"Missing generated skill: {adapter_rel}/{skill}/SKILL.md")
            continue
        if not marker.is_file():
            errors.append(f"Missing generated metadata: {adapter_rel}/{skill}")
            continue
        content = skill_md.read_text(encoding="utf-8", errors="ignore")
        if "# DO NOT EDIT: generated by DeltaFuse installer." not in content:
            errors.append(f"Generated skill is not marked DO NOT EDIT: {adapter_rel}/{skill}")
        meta_content = marker.read_text(encoding="utf-8", errors="ignore")
        if lock_version and f"generated_by: deltafuse@{lock_version}" not in meta_content:
            errors.append(f"Generated skill version mismatch: {adapter_rel}/{skill}")
        if lock_hash and f"content_hash: {lock_hash}" not in meta_content:
            errors.append(f"Generated skill hash mismatch: {adapter_rel}/{skill}")
    return errors
