"""Product installer and framework updater for DeltaFuse 2.0."""

from __future__ import annotations
import os
import re
import shutil
from pathlib import Path
from typing import NamedTuple
import yaml
from deltafuse.core.hasher import compute_framework_content_hash


class InstallResult(NamedTuple):
    target_dir: Path
    version: str
    content_hash: str
    skills_installed: int


class InstallationError(Exception):
    """Raised when product installation or upgrade fails."""
    pass


TEMPLATE_MAPPINGS = [
    ("process/templates/AGENTS.md", "AGENTS.md"),
    ("process/templates/.deltafuse/config.yaml", ".deltafuse/config.yaml"),
    ("process/templates/docs/intake/README.md", "docs/intake/README.md"),
    ("process/templates/docs/changes/README.md", "docs/changes/README.md"),
    ("process/templates/docs/spec/README.md", "docs/spec/README.md"),
    ("process/templates/docs/spec/context.md", "docs/spec/context.md"),
    ("process/templates/docs/spec/_capabilities.yaml", "docs/spec/_capabilities.yaml"),
    ("process/templates/docs/decisions/README.md", "docs/decisions/README.md"),
    ("process/templates/docs/decisions/DEC-0000-template.md", "docs/decisions/DEC-0000-template.md"),
    ("process/templates/docs/archive/README.md", "docs/archive/README.md"),
    ("process/templates/docs/archive/intake/README.md", "docs/archive/intake/README.md"),
    ("process/templates/docs/archive/changes/README.md", "docs/archive/changes/README.md"),
    ("process/templates/CHANGELOG.md", "CHANGELOG.md"),
]

DIRECTORIES_TO_CREATE = [
    ".deltafuse",
    "docs/intake",
    "docs/changes",
    "docs/spec",
    "docs/decisions",
    "docs/archive/intake",
    "docs/archive/changes",
]


def _copy_template_file(framework_root: Path, target_root: Path, src_rel: str, dst_rel: str) -> bool:
    """Copies template file to target if target does not already exist. Returns True if created."""
    src = framework_root / src_rel
    dst = target_root / dst_rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        return False
    shutil.copyfile(src, dst)
    return True


def _install_generated_skills(framework_root: Path, target_root: Path, adapter_rel: str, version: str, content_hash: str) -> int:
    adapter_root = target_root / adapter_rel
    adapter_root.mkdir(parents=True, exist_ok=True)

    skills_src = framework_root / "process" / "skills"
    if not skills_src.is_dir():
        return 0

    count = 0
    for skill_dir in skills_src.iterdir():
        if not skill_dir.is_dir():
            continue
        skill_name = skill_dir.name
        dst_skill = adapter_root / skill_name
        marker_file = dst_skill / ".deltafuse-generated.yaml"

        if dst_skill.exists():
            if not marker_file.is_file():
                # Non-generated skill, preserve it
                continue
            shutil.rmtree(dst_skill)

        shutil.copytree(skill_dir, dst_skill)

        # Inject DO NOT EDIT banner into SKILL.md
        skill_md = dst_skill / "SKILL.md"
        if skill_md.is_file():
            content = skill_md.read_text(encoding="utf-8")
            banner = (
                f"---\n"
                f"# DO NOT EDIT: generated by DeltaFuse installer.\n"
                f"# deltafuse-version: {version}\n"
                f"# deltafuse-source: deltafuse://v{version}/skills/{skill_name}\n"
                f"# deltafuse-content-hash: sha256:{content_hash}\n"
            )
            content = re.sub(r"\A---\r?\n", banner, content)
            skill_md.write_text(content, encoding="utf-8")

        marker_content = (
            f"generated_by: deltafuse@{version}\n"
            f"source: deltafuse://v{version}/skills/{skill_name}\n"
            f"content_hash: sha256:{content_hash}\n"
        )
        marker_file.write_text(marker_content, encoding="utf-8")
        count += 1

    return count


def install(
    target_dir: Path | str = ".",
    force: bool = False,
    framework_root: Path | str | None = None,
) -> InstallResult:
    """
    Installs or updates DeltaFuse product layout in target_dir.
    """
    target_root = Path(target_dir).resolve()
    target_root.mkdir(parents=True, exist_ok=True)

    if framework_root is None:
        framework_root = Path(__file__).resolve().parent.parent.parent.parent
    else:
        framework_root = Path(framework_root).resolve()

    version_file = framework_root / "VERSION"
    if not version_file.is_file():
        raise InstallationError(f"VERSION file not found in framework root: {framework_root}")
    version = version_file.read_text(encoding="utf-8").strip()

    content_hash = compute_framework_content_hash(framework_root)

    lock_path = target_root / ".deltafuse" / "lock.yaml"
    if lock_path.is_file() and not force:
        lock_text = lock_path.read_text(encoding="utf-8")
        if f"content_hash: sha256:{content_hash}" not in lock_text:
            raise InstallationError("A different DeltaFuse lock already exists. Rerun with --force for an explicit upgrade.")

    # Create target directories
    for d in DIRECTORIES_TO_CREATE:
        (target_root / d).mkdir(parents=True, exist_ok=True)

    config_path = target_root / ".deltafuse" / "config.yaml"
    config_existed = config_path.is_file()

    # Copy template files
    for src_rel, dst_rel in TEMPLATE_MAPPINGS:
        _copy_template_file(framework_root, target_root, src_rel, dst_rel)

    # Determine effective source and update config.yaml if needed
    config_source = None
    if config_path.is_file():
        config_text = config_path.read_text(encoding="utf-8")
        source_match = re.search(r"(?m)^\s{2}source:\s*(\S+)\s*$", config_text)
        if source_match:
            config_source = source_match.group(1)

    if config_source and config_source != "deltafuse" and not config_source.startswith("deltafuse://"):
        effective_source = config_source
    else:
        effective_source = f"deltafuse://v{version}"

    if config_path.is_file() and (not config_existed or force):
        config_content = config_path.read_text(encoding="utf-8")
        if not re.search(r"(?m)^\s{2}version:\s*\S+\s*$", config_content):
            raise InstallationError("Cannot update framework version: .deltafuse/config.yaml has no indented version field.")
        config_content = re.sub(
            r"(?m)^(\s{2}version:\s*)\S+(\s*)$",
            f"\\g<1>{version}\\g<2>",
            config_content,
            count=1,
        )
        if re.search(r"(?m)^\s{2}source:\s*(deltafuse|deltafuse://\S*)\s*$", config_content):
            config_content = re.sub(
                r"(?m)^(\s{2}source:\s*)\S+(\s*)$",
                f"\\g<1>{effective_source}\\g<2>",
                config_content,
                count=1,
            )
        config_path.write_text(config_content, encoding="utf-8")

    # Write lock.yaml
    lock_content = (
        f"schema_version: 2\n"
        f"framework:\n"
        f"  version: {version}\n"
        f"  source: {effective_source}\n"
        f"  content_hash: sha256:{content_hash}\n"
    )
    lock_path.write_text(lock_content, encoding="utf-8")

    # Read adapter roots from config.yaml
    adapter_roots: list[str] = []
    if config_path.is_file():
        try:
            config_dict = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
            adapters_section = config_dict.get("adapters", {})
            if isinstance(adapters_section, dict):
                roots = adapters_section.get("roots", [])
                if isinstance(roots, list):
                    adapter_roots = [str(r).strip() for r in roots if r]
        except Exception:
            pass

    if not adapter_roots:
        adapter_roots = [".agents/skills", ".cursor/skills", ".gemini/skills"]

    total_skills = 0
    for root_rel in adapter_roots:
        total_skills += _install_generated_skills(framework_root, target_root, root_rel, version, content_hash)

    return InstallResult(
        target_dir=target_root,
        version=version,
        content_hash=content_hash,
        skills_installed=total_skills,
    )
