"""Write envelope and git-diff guard (kernel, no LLM)."""

from __future__ import annotations

import json
from pathlib import Path
import subprocess
from typing import Any

import yaml

from deltafuse.core.context import (
    DEFAULT_CHANGE_ROUTE,
    PHASE_CONTRACTS,
    load_change_route,
    matches_contract_globs,
    path_is_listed,
    phase_allowed_paths,
    phase_write_globs,
    posix_relpath,
)
from deltafuse.core.lock import LEASH_MODES, normalize_leash_mode
from deltafuse.core.frontmatter import parse_frontmatter
from deltafuse.core.queue import WorkItem

DEFAULT_LEASH_MODE = "enforce"
HOOK_MARKER = "Generated by DeltaFuse installer. DO NOT EDIT."
HOOK_SCRIPT = """#!/bin/sh
# Generated by DeltaFuse installer. DO NOT EDIT.
root=$(git rev-parse --show-toplevel) || exit 1
cd "$root" || exit 1
py="${DELTAFUSE_PYTHON:-python}"
exec "$py" -m deltafuse leash "$root"
"""

CODE_WRITE_GLOBS = (
    "src/**",
    "tests/**",
    "deploy/**",
    "docs/ops/**",
    "ops/**",
)
SPEC_WRITE_GLOBS = ("docs/spec/**",)
PRODUCT_WRITE_GLOBS = CODE_WRITE_GLOBS + SPEC_WRITE_GLOBS
EXEMPT_EXACT = frozenset(
    {
        "AGENTS.md",
        "CHANGELOG.md",
        ".deltafuse/lock.yaml",
        ".deltafuse/config.yaml",
    }
)
EXEMPT_GLOBS = (
    ".git/**",
    ".deltafuse/**",
    "docs/intake/**",
    "docs/archive/**",
    # Interpreter caches: running the Red/Green tests writes them, and the
    # Worker cannot avoid it (q0 run 20260921T111852Z: declare refused over
    # src/ratelimit/__pycache__/*.pyc). fnmatch `*` crosses `/`.
    "*.pyc",
    "__pycache__/*",
    "*/__pycache__/*",
    ".pytest_cache/*",
    "*/.pytest_cache/*",
)
EXEMPT_NAMES = frozenset({"README.md", "README.ru.md"})
CHANGE_ARTIFACT_GLOB = "docs/changes/**"
# DF3-007: Core journals change only through the deltafuse CLI. The journals a
# lifecycle step legitimately appends to are verified; the trust roots never
# belong in a Worker diff.
CORE_JOURNALS = frozenset({"gate-journal.jsonl", "journal-head", "transitions.jsonl"})
CORE_OWNED = CORE_JOURNALS | {"trusted-keys.yaml"}
# Receipt kinds the Core appends to transitions.jsonl: `advance` (transition),
# `decide` unblocking a Change (unblock), `deltafuse state` (artifact-status).
CORE_RECEIPT_KINDS = frozenset({"transition", "unblock", "artifact-status"})



class LeashError(Exception):
    """Product root / git / queue error before a diff can be judged."""


def _unique(items: list[str]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for raw in items:
        if not isinstance(raw, str):
            continue
        text = raw.replace("\\", "/").strip()
        if not text or text in seen:
            continue
        seen.add(text)
        out.append(text)
    return out


def load_leash_mode(product_root: Path, *, missing: str = DEFAULT_LEASH_MODE) -> str:
    """CLI default when the key is absent is enforce. Hook install uses missing='off'."""
    path = product_root / ".deltafuse" / "config.yaml"
    if not path.is_file():
        return missing
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception:
        return missing
    if not isinstance(data, dict):
        return missing
    workflow = data.get("workflow")
    if not isinstance(workflow, dict):
        return missing
    raw = workflow.get("leash")
    if raw is None:
        return missing
    mode = normalize_leash_mode(raw)
    return mode if mode is not None else missing


def load_baseline(product_root: Path) -> str:
    path = product_root / ".deltafuse" / "config.yaml"
    if not path.is_file():
        return "draft"
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception:
        return "draft"
    if not isinstance(data, dict):
        return "draft"
    project = data.get("project")
    if not isinstance(project, dict):
        return "draft"
    raw = str(project.get("baseline") or "draft").strip().lower()
    if raw == "accepted":
        return "accepted"
    return "draft"


def _task_path_lists(product_root: Path, item: WorkItem) -> tuple[list[str], list[str]]:
    if not item.task_path:
        return [], []
    path = product_root / item.task_path
    if not path.is_file():
        return [], []
    try:
        meta, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
    except Exception:
        return [], []
    if not isinstance(meta, dict):
        return [], []
    allowed = [row for row in (meta.get("allowed_paths") or []) if isinstance(row, str)]
    forbidden = [row for row in (meta.get("forbidden_paths") or []) if isinstance(row, str)]
    return allowed, forbidden


def _minus_forbidden(globs: list[str], forbidden: list[str]) -> list[str]:
    if not forbidden:
        return globs
    return [row for row in globs if not path_is_listed(row, forbidden)]


def _change_dir(product_root: Path, item: WorkItem) -> Path | None:
    if not item.path:
        return None
    path = product_root / item.path
    if path.is_dir():
        return path
    return None


def envelope_write_globs(item: WorkItem, product_root: Path) -> list[str]:
    step = item.step or ""
    if item.allowed_write:
        writes = list(item.allowed_write)
    elif step in PHASE_CONTRACTS:
        writes = list(phase_write_globs(step, DEFAULT_CHANGE_ROUTE))
    else:
        writes = []
    change_dir = _change_dir(product_root, item)
    route = DEFAULT_CHANGE_ROUTE
    if change_dir is not None:
        route, _ = load_change_route(change_dir)
        route = route or DEFAULT_CHANGE_ROUTE
        if not item.allowed_write:
            writes = list(phase_write_globs(step, route))
    allowed_paths, forbidden = _task_path_lists(product_root, item)
    if step in {"declare", "implement"} and allowed_paths:
        phase = phase_write_globs(step, route)
        change_side = [glob for glob in phase if glob.replace("\\", "/").startswith("docs/changes")]
        test_side = [glob for glob in phase if glob.replace("\\", "/").startswith("tests")]
        product_side = [path for path in allowed_paths if matches_contract_globs(path, phase)]
        # A task's forbidden_paths bound its product and test scope. They never
        # remove the Change's own files: evidence is written by `deltafuse
        # evidence`, and a task forbidding `docs/**` made that evidence read as
        # a write outside the envelope (q0 run 20260921T130115Z).
        return _unique(change_side + _minus_forbidden(test_side + product_side, forbidden))
    return _unique(_minus_forbidden(writes, forbidden))


def envelope_read_globs(item: WorkItem) -> list[str]:
    if item.allowed_read:
        return _unique(list(item.allowed_read))
    if item.step:
        return _unique(phase_allowed_paths(item.step, "read"))
    return []


def build_envelope(item: WorkItem | None, product_root: Path) -> dict[str, Any] | None:
    """Write envelope for a ready Worker step. None when the Worker must not write."""
    if item is None or item.kind != "ready" or not item.step:
        return None
    return {
        "step": item.step,
        "change": item.change_id,
        "task": item.task,
        "write": envelope_write_globs(item, product_root),
        "read": envelope_read_globs(item),
    }


def path_in_envelope(rel_path: str, write_globs: list[str]) -> bool:
    return matches_contract_globs(posix_relpath(rel_path), write_globs)


def is_exempt_path(rel_path: str) -> bool:
    rel = posix_relpath(rel_path)
    if rel in EXEMPT_EXACT:
        return True
    name = rel.rsplit("/", 1)[-1]
    if name in EXEMPT_NAMES:
        return True
    if matches_contract_globs(rel, EXEMPT_GLOBS):
        return True
    return False


def is_product_path(rel_path: str, *, baseline: str = "draft") -> bool:
    rel = posix_relpath(rel_path)
    if matches_contract_globs(rel, CODE_WRITE_GLOBS):
        return True
    if baseline == "accepted" and matches_contract_globs(rel, SPEC_WRITE_GLOBS):
        return True
    return False


def is_change_artifact(rel_path: str) -> bool:
    return matches_contract_globs(posix_relpath(rel_path), [CHANGE_ARTIFACT_GLOB])


def collect_ready_envelopes(queue: Any, product_root: Path, halt: Any) -> list[dict[str, Any]]:
    """Envelopes of ready Worker steps. Empty when through-mode is halted."""
    if halt is not None:
        return []
    out: list[dict[str, Any]] = []
    for item in getattr(queue, "ready", []) or []:
        env = build_envelope(item, product_root)
        if env:
            out.append(env)
    return out


def _covered_by(rel_path: str, envelopes: list[dict[str, Any]]) -> dict[str, Any] | None:
    for env in envelopes:
        writes = env.get("write")
        globs = [row for row in writes if isinstance(row, str)] if isinstance(writes, list) else []
        if path_in_envelope(rel_path, globs):
            return env
    return None



DEFAULT_CAPABILITY_ROOTS = ("src/**", "tests/**", "docs/spec/**")


def capability_roots(product_root: Path | None) -> tuple[str, ...]:
    """Capability catalog roots (DF3-006): config workflow.code_roots wins."""
    if product_root is None:
        return DEFAULT_CAPABILITY_ROOTS
    try:
        data = yaml.safe_load(
            (product_root / ".deltafuse" / "config.yaml").read_text(encoding="utf-8")
        ) or {}
    except Exception:
        return DEFAULT_CAPABILITY_ROOTS
    workflow = data.get("workflow") if isinstance(data, dict) else None
    roots = workflow.get("code_roots") if isinstance(workflow, dict) else None
    if isinstance(roots, list) and roots:
        return tuple(str(r) for r in roots)
    return DEFAULT_CAPABILITY_ROOTS


def _glob_covers(task_glob: str, slice_glob: str) -> bool:
    """True when task_glob is bounded by slice_glob (path-prefix semantics)."""
    norm = lambda g: g.replace("\\", "/").strip().lstrip("/")
    task, sl = norm(task_glob), norm(slice_glob)
    if task == sl:
        return True
    base = sl[:-3] if sl.endswith("/**") else sl
    if sl.endswith("/**"):
        return task == base or task.startswith(base + "/")
    return task == sl


def task_envelope_errors(change_path: Path, task_id: str | None = None) -> list[str]:
    """SEC-04 / DF3-006: task allowed_paths must stay inside their slice
    target_paths (or the capability-catalog roots when the slice declares
    none). A task cannot widen its write envelope by editing YAML."""
    from deltafuse.core.frontmatter import parse_frontmatter

    tasks_dir = change_path / "tasks"
    if not tasks_dir.is_dir():
        return []
    slice_bounds: dict[str, list[str]] = {}
    slices_dir = change_path / "slices"
    if slices_dir.is_dir():
        for sf in sorted(list(slices_dir.glob("*.md")) + list(slices_dir.glob("*.yaml"))):
            try:
                meta, _ = parse_frontmatter(sf.read_text(encoding="utf-8"))
            except Exception:
                continue
            bounds = [str(g) for g in meta.get("target_paths") or []]
            if bounds:
                slice_bounds[str(meta.get("id") or sf.stem)] = bounds

    # A slice that declares no target_paths is bounded by the capability roots
    # plus what the Change's route may write in Declare and Implement. The
    # roots alone (src, tests, docs/spec) never cover an ops route's
    # deploy/**, docs/ops/**, ops/**: every ops task was blocked, and the slice
    # that could widen it is outside the decompose envelope. The route's own
    # write globs are already the widest envelope it has.
    route, _ = load_change_route(change_path)
    route_globs = [
        glob
        for phase in ("declare", "implement")
        for glob in phase_write_globs(phase, route or DEFAULT_CHANGE_ROUTE)
        if not glob.replace("\\", "/").startswith("docs/changes")
    ]
    default_bounds = list(dict.fromkeys(list(DEFAULT_CAPABILITY_ROOTS) + route_globs))

    errors: list[str] = []
    for tf in sorted(tasks_dir.glob("*.md")):
        try:
            meta, _ = parse_frontmatter(tf.read_text(encoding="utf-8"))
        except Exception:
            continue
        tid = str(meta.get("id") or tf.stem)
        if task_id is not None and tid != task_id:
            continue
        sid = str(meta.get("slice") or "")
        bounds = slice_bounds.get(sid) or default_bounds
        for raw in meta.get("allowed_paths") or []:
            task_glob = str(raw)
            if not any(_glob_covers(task_glob, g) for g in bounds):
                errors.append(
                    f"Task {tid}: allowed_paths '{task_glob}' escapes slice '{sid}' target_paths"
                )
    return errors


def _git_show(product_root: Path, ref: str, rel_path: str) -> str | None:
    """File content at a revision; None when the file (or the revision) is absent."""
    proc = subprocess.run(
        ["git", "show", f"{ref}:{rel_path}"],
        cwd=product_root,
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        return None
    return proc.stdout.decode("utf-8", errors="replace")


def _nonempty_lines(text: str | None) -> list[str]:
    return [line.strip() for line in (text or "").splitlines() if line.strip()]


def _journal_lines(
    product_root: Path, rel_path: str, *, base: str | None, head: str | None
) -> tuple[list[str], list[str]]:
    old = _nonempty_lines(_git_show(product_root, base or "HEAD", rel_path))
    if head:
        new = _nonempty_lines(_git_show(product_root, head, rel_path))
    else:
        path = product_root / rel_path
        new = _nonempty_lines(path.read_text(encoding="utf-8") if path.is_file() else None)
    return old, new


def _change_dirs(product_root: Path) -> dict[str, Path]:
    """Change id -> directory for every live Change package."""
    out: dict[str, Path] = {}
    for change_yaml in sorted((product_root / "docs" / "changes").glob("*/change.yaml")):
        try:
            data = yaml.safe_load(change_yaml.read_text(encoding="utf-8")) or {}
        except Exception:
            data = {}
        change_id = data.get("id") if isinstance(data, dict) else None
        out[str(change_id or change_yaml.parent.name)] = change_yaml.parent
    return out


def core_journal_errors(
    product_root: Path,
    name: str,
    *,
    base: str | None = None,
    head: str | None = None,
) -> list[str]:
    """DF3-007: why a Core journal diff is not a Core-shaped append (empty = valid).

    The Worker runs `deltafuse advance` and the human runs `deltafuse decide`
    inside the same working tree, so the journals legitimately change between
    commits. A diff is accepted only when it appends entries the Core would have
    written: existing lines untouched, every transition receipt digest intact
    and the chain replayable, the gate journal chain and head verified.
    """
    from deltafuse.core import gate_receipts
    from deltafuse.core.transitions import _receipt, receipt_chain_errors

    root = Path(product_root)
    if name == "journal-head":
        # The head digest moves with every gate receipt; it is valid exactly
        # when it matches the verified gate journal.
        return gate_receipts.journal_errors(root)
    rel = f".deltafuse/{name}"
    old, new = _journal_lines(root, rel, base=base, head=head)
    if new[: len(old)] != old:
        return ["existing entries were edited, removed or reordered; Core journals are append-only"]
    appended = new[len(old):]
    errors: list[str] = []
    if name == "transitions.jsonl":
        touched: set[str] = set()
        for number, raw in enumerate(appended, start=len(old) + 1):
            try:
                entry = json.loads(raw)
            except json.JSONDecodeError:
                errors.append(f"line {number} is not JSON")
                continue
            if not isinstance(entry, dict) or entry.get("kind") not in CORE_RECEIPT_KINDS:
                errors.append(f"line {number} is not a Core transition receipt")
                continue
            body = {key: value for key, value in entry.items() if key != "receipt"}
            if entry.get("receipt") != _receipt(body):
                errors.append(f"line {number}: receipt digest does not match the entry")
                continue
            if isinstance(entry.get("change"), str):
                touched.add(entry["change"])
        if errors:
            return errors
        dirs = _change_dirs(root)
        for change_id in sorted(touched):
            change_dir = dirs.get(change_id)
            if change_dir is not None:
                errors.extend(
                    f"{change_id}: {err}" for err in receipt_chain_errors(root, change_dir)
                )
        return errors
    if name == "gate-journal.jsonl":
        for number, raw in enumerate(appended, start=len(old) + 1):
            try:
                entry = json.loads(raw)
            except json.JSONDecodeError:
                errors.append(f"line {number} is not JSON")
                continue
            # journal_errors skips legacy lines, but has_click still reads
            # them: an appended line without the current receipt format
            # would count as a click without any integrity claim.
            if not isinstance(entry, dict) or entry.get("receipt_version") != gate_receipts.RECEIPT_VERSION:
                errors.append(f"line {number} is not a current-format gate receipt")
        if errors:
            return errors
        return gate_receipts.journal_errors(root)
    return [f"unknown Core journal '{name}'"]


def _content_at(product_root: Path, rel_path: str, *, head: str | None) -> str | None:
    if head:
        return _git_show(product_root, head, rel_path)
    path = product_root / rel_path
    return path.read_text(encoding="utf-8") if path.is_file() else None


def core_status_writes(
    product_root: Path,
    *,
    base: str | None = None,
    head: str | None = None,
) -> dict[str, list[str]]:
    """Task and slice files the Core rewrote through `deltafuse state` since ``base``.

    `deltafuse state` is how a Worker asks the Core to move a slice or task
    status; the Core rewrites the frontmatter and appends an artifact-status
    receipt. Those files lie outside the step envelope on purpose - a Worker
    must not hand-edit them - so the guard recognises the Core's rewrite by its
    receipt and by its content: only `status` changed, from the first receipt's
    `from` to the last receipt's `to`, the rest of the frontmatter and the body
    as before. Maps each path to the reasons it fails (empty = a pure Core
    status write).
    """
    root = Path(product_root)
    old, new = _journal_lines(root, ".deltafuse/transitions.jsonl", base=base, head=head)
    if new[: len(old)] != old:
        return {}  # core_journal_errors reports the rewrite; nothing is vouched for
    dirs = _change_dirs(root)
    moves: dict[str, list[dict[str, Any]]] = {}
    for raw in new[len(old):]:
        try:
            entry = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict) or entry.get("kind") != "artifact-status":
            continue
        folder = {"task": "tasks", "slice": "slices"}.get(str(entry.get("artifact")))
        change_dir = dirs.get(str(entry.get("change")))
        if folder is None or change_dir is None or not isinstance(entry.get("artifact_id"), str):
            continue
        home = (change_dir / folder).relative_to(root).as_posix()
        rel = (change_dir / folder / f"{entry['artifact_id']}.md").relative_to(root).as_posix()
        recorded = entry.get("path")
        if isinstance(recorded, str):
            # A task file may be TASK-NNN-<slug>.md; the Core records which one
            # it rewrote. Only a file of this Change's folder is ever accepted.
            recorded = posix_relpath(recorded)
            if recorded.startswith(home + "/") and "/" not in recorded[len(home) + 1:]:
                rel = recorded
        moves.setdefault(rel, []).append(entry)

    out: dict[str, list[str]] = {}
    for rel, entries in moves.items():
        reasons: list[str] = []
        try:
            before_meta, before_body = parse_frontmatter(_git_show(root, base or "HEAD", rel) or "")
            after_meta, after_body = parse_frontmatter(_content_at(root, rel, head=head) or "")
        except Exception as ex:
            out[rel] = [f"cannot compare with the base: {ex}"]
            continue
        if before_meta.get("status") != entries[0].get("from"):
            reasons.append(f"status at the base is not the receipt's '{entries[0].get('from')}'")
        if after_meta.get("status") != entries[-1].get("to"):
            reasons.append(f"status is not the receipt's '{entries[-1].get('to')}'")
        rest_before = {k: v for k, v in before_meta.items() if k != "status"}
        rest_after = {k: v for k, v in after_meta.items() if k != "status"}
        if rest_before != rest_after:
            reasons.append("frontmatter changed beyond status")
        if before_body.strip() != after_body.strip():
            reasons.append("body changed")
        out[rel] = reasons
    return out


def collect_chain_envelopes(
    product_root: Path,
    *,
    base: str | None = None,
    dirty: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Envelopes of the lifecycle steps each Change worked through since ``base``.

    The ready queue names only the next step, so it alone judges a finished
    step's writes against the step that follows it: request.md written by
    intake reads as outside the analyze envelope, and a commit right after
    `deltafuse advance` is refused. The steps are taken from the transition
    receipts, which core_journal_errors verifies: from the step after the last
    gate at ``base`` up to the step after the last gate now.

    Declare and implement are per task, and task progress is not in the
    transition chain. Their envelopes come from the tasks whose file changed
    since ``base`` - `deltafuse state` rewrites the task file on every task
    transition - so a task the Worker never touched adds no paths.
    """
    from deltafuse.core.queue import _load_tasks
    from deltafuse.core.steps import STEP_CONTRACTS, STEP_ORDER

    root = Path(product_root)
    gate_step = {spec["gate"]: step for step, spec in STEP_CONTRACTS.items()}

    def last_gates(lines: list[str]) -> dict[str, str]:
        out: dict[str, str] = {}
        for raw in lines:
            try:
                entry = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if (
                isinstance(entry, dict)
                and entry.get("kind") == "transition"
                and isinstance(entry.get("change"), str)
                and entry.get("gate") in gate_step
            ):
                out[entry["change"]] = entry["gate"]
        return out

    def step_after(gate: str | None) -> int:
        if gate is None:
            return 0
        return min(STEP_ORDER.index(gate_step[gate]) + 1, len(STEP_ORDER) - 1)

    rel = ".deltafuse/transitions.jsonl"
    at_base, now = _journal_lines(root, rel, base=base, head=None)
    base_last, now_last = last_gates(at_base), last_gates(now)
    changed = {posix_relpath(path) for path in (dirty or [])}

    envelopes: list[dict[str, Any]] = []
    for change_id, change_dir in _change_dirs(root).items():
        low, high = step_after(base_last.get(change_id)), step_after(now_last.get(change_id))
        if high < low:
            continue  # a rewound chain is receipt_chain_errors' business, not a wider fence
        rel_dir = change_dir.relative_to(root).as_posix()
        for step in STEP_ORDER[low : high + 1]:
            spec = STEP_CONTRACTS[step]
            items: list[WorkItem] = []
            if step in {"declare", "implement"}:
                for task_id, _, task_file in _load_tasks(change_dir):
                    task_rel = task_file.relative_to(root).as_posix()
                    if task_rel in changed:
                        items.append(
                            WorkItem(
                                kind="ready", step=step, skill=spec["skill"], gate=spec["gate"],
                                change_id=change_id, path=rel_dir, task=task_id,
                                task_path=task_rel, reason="receipt chain since base",
                            )
                        )
            else:
                items.append(
                    WorkItem(
                        kind="ready", step=step, skill=spec["skill"], gate=spec["gate"],
                        change_id=change_id, path=rel_dir, task=None, task_path=None,
                        reason="receipt chain since base",
                    )
                )
            for item in items:
                env = build_envelope(item, root)
                if env:
                    envelopes.append(env)
    return envelopes


def check_paths(
    rel_paths: list[str],
    envelopes: list[dict[str, Any]] | dict[str, Any] | None = None,
    *,
    envelope: dict[str, Any] | None = None,
    baseline: str = "draft",
    product_root: Path | None = None,
    base: str | None = None,
    head: str | None = None,
) -> list[str]:
    """Return violation messages for dirty paths.

    A path is allowed when a ready envelope covers it. Code/ops/deploy
    paths with no covering Change are orphans. `docs/spec/**` is an
    orphan only after `project.baseline: accepted` (Bootstrap may write
    spec while the baseline is draft). Ready step + uncovered Change
    artifact is still an LS-002 miss.

    Core journals (DF3-007): with ``product_root`` they are verified against
    ``base`` instead of refused outright, because every `deltafuse advance`
    and `decide` appends to them; without it any change is refused.
    """
    if isinstance(envelopes, dict):
        env_list = [envelopes]
    elif envelopes is None:
        env_list = [envelope] if envelope is not None else []
    else:
        env_list = list(envelopes)
    errors: list[str] = []
    steps = [str(env.get("step") or "?") for env in env_list]
    step_label = ", ".join(dict.fromkeys(steps)) if steps else ""
    status_writes = (
        core_status_writes(product_root, base=base, head=head) if product_root is not None else {}
    )
    for raw in _unique(rel_paths):
        # DF3-007 runs before the exemptions: `.deltafuse/**` is exempt as a
        # whole, so checking it second would make the Core-owned guard dead code.
        top, _, tail = posix_relpath(raw).partition("/")
        if top == ".deltafuse" and tail in CORE_OWNED:
            if product_root is not None and tail in CORE_JOURNALS:
                reasons = core_journal_errors(product_root, tail, base=base, head=head)
                if not reasons:
                    continue
                errors.extend(
                    f"leash: '{raw}' changed outside the deltafuse CLI: {reason} (DF3-007)"
                    for reason in reasons
                )
                continue
            errors.append(
                f"leash: '{raw}' is Core-owned; mutate it only through the deltafuse CLI (DF3-007)"
            )
            continue
        if raw.startswith(".git/") or is_exempt_path(raw):
            continue
        if _covered_by(raw, env_list) is not None:
            continue
        status_reasons = status_writes.get(posix_relpath(raw))
        if status_reasons is not None:
            if not status_reasons:
                continue  # a `deltafuse state` rewrite, vouched for by its receipt
            errors.extend(
                f"leash: '{raw}' is outside the {step_label} write envelope and not a pure "
                f"Core status write: {reason}"
                for reason in status_reasons
            )
            continue
        if is_product_path(raw, baseline=baseline):
            if not env_list:
                errors.append(f"leash: '{raw}' is not covered by any Change")
            else:
                errors.append(
                    f"leash: '{raw}' is outside the {step_label} write envelope"
                )
            continue
        if is_change_artifact(raw) and env_list:
            errors.append(
                f"leash: '{raw}' is outside the {step_label} write envelope"
            )
    return errors



def git_dirty_paths(
    product_root: Path,
    *,
    base: str | None = None,
    head: str | None = None,
) -> list[str]:
    """Changed paths as repo-relative posix names.

    DF3-003 / SEC-01: pass ``base`` (and optionally ``head``) with exact SHAs to
    diff a commit range — a clean PR/push checkout has no local diff, so CI must
    judge the committed range. Untracked files remain a separate always-on check.
    """
    root = product_root.resolve()
    probe = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if probe.returncode != 0:
        err = (probe.stderr or probe.stdout or "git rev-parse failed").strip()
        raise LeashError(f"leash needs a git repository: {err}")
    diff_args = ["git", "diff", "--name-only"]
    if base:
        diff_args.append(f"{base}..{head or 'HEAD'}")
    else:
        diff_args.append("HEAD")
    tracked = subprocess.run(
        diff_args,
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if tracked.returncode != 0:
        err = (tracked.stderr or tracked.stdout or "git diff failed").strip()
        raise LeashError(f"leash could not read git diff: {err}")
    untracked = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if untracked.returncode != 0:
        err = (untracked.stderr or untracked.stdout or "git ls-files failed").strip()
        raise LeashError(f"leash could not list untracked files: {err}")
    names = (tracked.stdout or "").splitlines() + (untracked.stdout or "").splitlines()
    out: list[str] = []
    for raw in names:
        text = raw.strip().replace("\\", "/")
        if not text:
            continue
        out.append(text)
    return _unique(out)


def _chmod_exec(path: Path) -> None:
    try:
        path.chmod(path.stat().st_mode | 0o111)
    except OSError:
        return


def _remove_marked_hook(path: Path) -> None:
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8", errors="replace")
    if HOOK_MARKER not in text:
        return
    path.unlink()


def _git_hooks_dir(product_root: Path) -> Path | None:
    git = product_root / ".git"
    if git.is_dir():
        return git / "hooks"
    return None


def sync_leash_hook(product_root: Path, mode: str) -> None:
    """Install or remove the local git pre-commit hook. Never git push.

    `off` removes a hook we generated. `advisory` and `enforce` write the
    same script (`deltafuse leash` already exits 0 in advisory). A foreign
    pre-commit without the installer marker is left alone; a copy still
    lands under `.deltafuse/hooks/` for chaining.
    """
    root = Path(product_root)
    normalized = str(mode or "").strip().lower()
    if normalized not in LEASH_MODES:
        normalized = "off"
    managed = root / ".deltafuse" / "hooks" / "pre-commit"
    hooks_dir = _git_hooks_dir(root)
    git_hook = (hooks_dir / "pre-commit") if hooks_dir is not None else None
    if normalized == "off":
        _remove_marked_hook(managed)
        if git_hook is not None:
            _remove_marked_hook(git_hook)
        return
    managed.parent.mkdir(parents=True, exist_ok=True)
    managed.write_text(HOOK_SCRIPT, encoding="utf-8", newline="\n")
    _chmod_exec(managed)
    if git_hook is None:
        return
    git_hook.parent.mkdir(parents=True, exist_ok=True)
    if git_hook.is_file():
        existing = git_hook.read_text(encoding="utf-8", errors="replace")
        if HOOK_MARKER not in existing:
            return
    git_hook.write_text(HOOK_SCRIPT, encoding="utf-8", newline="\n")
    _chmod_exec(git_hook)
